### ISSUE TITLE
Key Error

### ISSUE THREAD

**Issue by mous1331** [Hyperclaw79/PokeBall-SelfBot#1]
![image](https://user-images.githubusercontent.com/19436148/37431498-52f98a86-27cd-11e8-8f91-1a74fb7288b4.png)
I get this after I start the bot, I followed the steps.

**Comment by Hyperclaw79** [comment]
Uhm no, replace the entire `os.environ` with the token. Not the path.
`os.environ` is for advanced usage where you can use environmental variables to hide your keys as local object on your own private system.

So, it should be `configs["token"] = "MXXX123......"`.
