### ISSUE TITLE
Unknown Error During Deployment.

### ISSUE THREAD

**Issue by wdfghj** [Hyperclaw79/PokeBall-SelfBot#10]
i've donewhat you asked.  i've even redownloaded it but it stil does not work. 
i get the same error everytime right now
![image](https://user-images.githubusercontent.com/38813420/39405150-298fd42e-4ba0-11e8-9225-36c4557b4f3f.png)
this is the code
![image](https://user-images.githubusercontent.com/38813420/39405153-403a4434-4ba0-11e8-90a2-1cd8cca0577f.png)
btw: i will change my token.

**Comment by wdfghj** [comment]
i sometimes get this to
![image](https://user-images.githubusercontent.com/38813420/39405175-a85bd0f0-4ba0-11e8-9bcc-137330e5e2c5.png)

**Comment by Hyperclaw79** [comment]
You'll keep getting the keyerror if you don't change your token. Get it again after changing your password, replace the token in the code with the new one and then try.

The latest error you posted seems like a unique one to you. Post the full Traceback (The error info starting from `Traceback`) to see where the error occurs. 

Make sure you're connected properly to the internet and no firewall/antivirus in blocking you.

**Comment by wdfghj** [comment]
Changed password, changed key, still there same error. On thé official pokecord catcher thé key works.

**Comment by wdfghj** [comment]
You have teamspeak? Maybe you can see yourself

**Comment by wdfghj** [comment]
TeamViewer*

**Comment by Hyperclaw79** [comment]
Sorry, I cannot that level of assistance where I take control of your PC itself. 
Also, I have noticed the obvious mistake there which everyone seems to be making.

It should be:
```py
configs["token"] = "Insert token here"
```
Not:
```py
configs["token"] = os.environ["Insert token here"]
```

**Comment by wdfghj** [comment]
UMG thanks it's working
