### ISSUE TITLE
embcheck = emb.title.startswith('A wild') fails

### ISSUE THREAD

**Issue by shanny** [Hyperclaw79/PokeBall-SelfBot#100]
# Title: embcheck = emb.title.startswith('A wild') fails

# Body:

## Problem:
The bot was not running in the channels even though I turned it on. I placed a few print statements throughout. None of my print statements printed in the case where embcheck = true, so I figured emb.title.startswith('A wild') was failing, so I printed the embed object out. I found that emb.title looks like it starts with " | A wild" or something like that. I assumed it would be easy enough to just change the embcheck to emb.description.startswith('Guess the'), so I made that change, tested it, and found the bot was auto catching pokemon again. Now I'm new to this and I'm not entirely sure how to submit a change/fix, so I figured I'd log this, if anyone has problems they can make the change themselves. I'd add the line but I haven't turned that functionality on in the python editor yet (I might have just downloaded it today) so, just ctrl+F guys.

## Steps to Reproduce:
List out the steps you took to come upon the error.

## config.json:
Most of the problems arise due to badly edited config.json. Hence post the contents of it within codeblocks. (Select the contents here and press code button on top.)

## Traceback and Screenshots:
Paste the Traceback/Error here using codeblocks.
Post relevant screenshots.

## Specs.
**OS**:
**Bot Version**:
**Python Version**:

**Comment by Hyperclaw79** [comment]
Already fixed in Premium Version. Not making changes here cause the autocatcher doesn't work anyway.
