### ISSUE TITLE
Pokecord

### ISSUE THREAD

**Issue by pok3rekt** [Hyperclaw79/PokeBall-SelfBot#107]
# Title: [Bug/Query/(leave empty)] ErrorName

# Body:

## Problem:
Hey I followeed everystep for your pokecord catcher but still cannot get it to work is this code still in date ? Also when i run the run.bat it closes instantly im not sure if this is supposed to happen orr how i fix the issue tks 

## Steps to Reproduce:
List out the steps you took to come upon the error.

## config.json:
Most of the problems arise due to badly edited config.json. Hence post the contents of it within codeblocks. (Select the contents here and press code button on top.)

## Traceback and Screenshots:
Paste the Traceback/Error here using codeblocks.
Post relevant screenshots.

## Specs.
**OS**:
**Bot Version**:
**Python Version**:

**Comment by Hyperclaw79** [comment]
It you're talking about the autocatcher part, it'll work only in Premium
Version.

If you're not able to launch the bot in general, make sure you have the
correct version of python, i.e., 3.6 and Git for Windows installed before
running setup.bat.

Read the closed issues for debugging purposes.

**Comment by Hyperclaw79** [comment]
Closing this as it is a local issue and got no response yet, assuming that the problem has been solved. Feel free to re-open it if the problem persists.

**Comment by pok3rekt** [comment]
sorry to bother you but I couldn't see clearly what the free version is for
and also how much I the autocatcher part

**Comment by Hyperclaw79** [comment]
The free version is intended for testing the bot out on your local system. It also has the auto-trade and other functions. (You'l have to go through the `pokeball.py` for a list of commands.) 

As for the pricing of the Premium Version and all other related details, scroll down to the [Donations Section](https://github.com/Hyperclaw79/PokeBall-SelfBot#donations) on the readme.

**Comment by pok3rekt** [comment]
File
"C:\Users\danie\OneDrive\Desktop\PokeBall-SelfBot-master\pokeball.py", line
51, in run
    super().run(self.configs['token'], bot=False)
  File
"C:\Users\danie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py",
line 568, in run
    return task.result()
  File
"C:\Users\danie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py",
line 488, in _silence_gathered
    fut.result()
  File
"C:\Users\danie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py",
line 476, in start
    await self.connect(reconnect=reconnect)
  File
"C:\Users\danie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py",
line 398, in connect
    await self._connect()
  File
"C:\Users\danie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py",
line 358, in _connect
    self.ws = await asyncio.wait_for(coro, timeout=180.0, loop=self.loop)
  File
"C:\Users\danie\AppData\Local\Programs\Python\Python37-32\lib\asyncio\tasks.py",
line 412, in wait_for
    return fut.result()
  File
"C:\Users\danie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\gateway.py",
line 199, in from_client
    ws = await websockets.connect(gateway, loop=client.loop, klass=cls,
compression=None)
  File
"C:\Users\danie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\websockets\client.py",
line 397, in __await__
    transport, protocol = yield from self._creating_connection
TypeError: cannot 'yield from' a coroutine object in a non-coroutine
generator
sys:1: RuntimeWarning: coroutine 'BaseEventLoop.create_connection' was
never awaited

C:\Users\danie\OneDrive\Desktop\PokeBall-SelfBot-master>timeout -1

Press any key to continue ... thats my error when i try to even run the bot
for the free version

**Comment by Hyperclaw79** [comment]
As clearly stated, you'll need Python 3.6.
But looks like you're running 3.7.

**Comment by Hyperclaw79** [comment]
Re-run setup.bat and make sure it is successful.
