### ISSUE TITLE
Deployment Issue

### ISSUE THREAD

**Issue by SwagmastrYT** [Hyperclaw79/PokeBall-SelfBot#108]
i cant run the bat file and this is what shows up when i try to run it

C:\Users\owner\Downloads\PokeBall-SelfBot-master\PokeBall-SelfBot-master>py -3 launcher.py
Traceback (most recent call last):
  File "launcher.py", line 2, in <module>
    from pokeball import PokeBall
  File "C:\Users\owner\Downloads\PokeBall-SelfBot-master\PokeBall-SelfBot-master\pokeball.py", line 2, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'

C:\Users\owner\Downloads\PokeBall-SelfBot-master\PokeBall-SelfBot-master>timeout -1

Press any key to continue ...

**Comment by Hyperclaw79** [comment]
Refer https://github.com/Hyperclaw79/PokeBall-SelfBot/issues/101.
Run the `setup.bat` only after installing both python 3.6 and Git for Windows.
