### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by gayman79** [Hyperclaw79/PokeBall-SelfBot#109]
# Title: syntax error

# Body:when i run it it says syntax error -1
@Hyperclaw79 

## Problem:
[![Screenshot from Gyazo](https://gyazo.com/4ba472a4f0e7cb3b7429201af322b2d9/raw)](https://gyazo.com/4ba472a4f0e7cb3b7429201af322b2d9)

## Steps to Reproduce:
i set up Config/json to put rayquaza seolgea and groudon to be prioritys saved it then ran setup, after i ran run.bat and i came across that message

## config.json:
Most of the problems arise due to badly edited config.json. Hence post the contents of it within codeblocks. (Select the contents here and press code button on top.)

## Traceback and Screenshots:
Paste the Traceback/Error here using codeblocks.
Post relevant screenshots.[![Screenshot from Gyazo](https://gyazo.com/4ba472a4f0e7cb3b7429201af322b2d9/raw)](https://gyazo.com/4ba472a4f0e7cb3b7429201af322b2d9)
[![Screenshot from Gyazo](https://gyazo.com/944051c1b6ed8ebee8d6dc6055e1e2dd/raw)](https://gyazo.com/944051c1b6ed8ebee8d6dc6055e1e2dd)

## Specs.
**OS**:
**Bot Version**:
**Python Version**:3.7

**Comment by gayman79** [comment]
help

**Comment by Hyperclaw79** [comment]
You need Python 3.6, not Python 3.7.
Also, do not run the bot as admin.
Re-run `setup.bat` after you change your python version.
