### ISSUE TITLE
requirements.txt error

### ISSUE THREAD

**Issue by kevzter15** [Hyperclaw79/PokeBall-SelfBot#113]
When ever I try setup.bat I always get “Could not open requirements file; [Errno 2] No such file or directory: ‘requirements.txt’”. Please help. Also my requirements.txt is just a link so I supposed to change it to something else or leave it and input something else other than setup.bat?

**Comment by Hyperclaw79** [comment]
You're supposed to download and extract all the contents locally. Not just
run it from there zip, which is what you're doing probably.
