### ISSUE TITLE
Autocatcher not working.

### ISSUE THREAD

**Issue by realtirey** [Hyperclaw79/PokeBall-SelfBot#115]
# Title: Autocatcher not working.

# Body: ?

## Problem:
When I run the run.bat file, the pokemon aren't being auto caught.

## Steps to Reproduce:
List out the steps you took to come upon the error.

## config.json:
```
"token": "not giving away that",
   "command_prefix": "P^",
   "priority": [
     
   ],
   "avoid": [],
   "catch_rate": 100,
   "delay": 0,
   "delay_on_priority": false,
   "restrict_duplicates": false,
   "max_duplicates": 100,
   "blacklists": [],
   "whitelists": [492328842254614537],
   "blacklist_guilds": [382316968394620938],
   "whitelist_guilds": [492328842254614533],
   "autolog": true,
   "update_checker": true,
   "auto_update": true,
   "autocatcher": true,
   "priority_only": false
}
```

## Traceback and Screenshots:
No screenshots really, just not working.

## Specs.
**OS**: Windows 10
**Bot Version**: 3.3.2
**Python Version**: 3.7

**Comment by Hyperclaw79** [comment]
No clue how you missed it but it's clearly mentioned in the readme in bold
that Autocatcher is Premium Version only.

**Comment by realtirey** [comment]
Well what is the point in someone using the selfbot anymore then e.e

**Comment by Hyperclaw79** [comment]
This is a just a demo version with auto-trade, mass-release, etc. and also
serves as a portal for the future Premium Version interested people.
Morever, this version isn't maintained anymore.  





On Fri, Sep 21, 2018 11:24 PM, realtirey notifications@github.com  wrote:
Well what is the point in someone using the selfbot anymore then e.e
