### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by realtirey** [Hyperclaw79/PokeBall-SelfBot#116]
Can you give me a list of commands for this selfbot? For example, the mass release feature. I have no clue how to use it!

**Comment by Hyperclaw79** [comment]
The Help command which showcases all the commands along with their usage is limited to the Premium Version.
If you wanna know what all commands you can use, go through the functions in `pokeball.py`, that start with `cmd_`.

**Comment by realtirey** [comment]
When I run pokeball.py, it opens and immediately closes.

**Comment by Hyperclaw79** [comment]
Open it with Visual Studio Code

**Comment by realtirey** [comment]
When I do so, it opens a ton of code with no functions as you described.

**Comment by Hyperclaw79** [comment]
Google what a python function is.

**Comment by realtirey** [comment]
Oh.

**Comment by Hyperclaw79** [comment]
After you complete P^pokelog, you just need to do P^mass_release dupes

**Comment by realtirey** [comment]
Thankyou! Does this command keep the highest IV of the dupes? Or highest
level?

**Comment by Hyperclaw79** [comment]
Highest level. IV logic is only available on the Premium Version.

**Comment by realtirey** [comment]
Now that's annoying. Looks like I wont be using this mass release feature. Thanks, bye.

**Comment by Hyperclaw79** [comment]
Well, that's why there are so many people willing to get the Premium Version as it is robust and feature rich. If you're expecting all those features on the public version then it's obvious that you will be disappointed. That's the whole reason why I listed out there Premium Version features beforehand in the readme.
