### ISSUE TITLE
Autocatcher not working because I don't have premium

### ISSUE THREAD

**Issue by ZUZ3** [Hyperclaw79/PokeBall-SelfBot#117]
# Title: [Bug/Query/(leave empty)] ErrorName
There's no error

# Body:
I have no clue how to work it I did everything it's told me to do.
## Problem:
the autocatcher won't launch or work
## Steps to Reproduce:
Nothing it just won't work
## config.json:
{
  "token": "MyToken",
  "command_prefix": "P^",
  "priority": [
    "Groudon",
    "Mew",
    "Machop",
    "Staryu"
  ],
  "avoid": [],
  "catch_rate": 90,
  "delay": 3,
  "delay_on_priority": false,
  "restrict_duplicates": true,
  "max_duplicates": 2,
  "blacklists": [],
  "whitelists": [ 483365474441101315 ],
  "blacklist_guilds": [ 382316968394620938 ],
  "whitelist_guilds": [ 365975655608745985 ],
  "autolog": true,
  "update_checker": true,
  "auto_update": true,
  "autocatcher": false,
  "priority_only": false
}

## Traceback and Screenshots:
![c__windows_system32_cmd exe 10_1_2018 10_23_06 am](https://user-images.githubusercontent.com/43752244/46294583-184e8280-c564-11e8-9f46-6d5ad07ae385.png)

## Specs.
**OS**:?
**Bot Version**:newest for free version
**Python Version**:newest

**Comment by Hyperclaw79** [comment]
Lol why open an issue when you already know the solution?
