### ISSUE TITLE
Not catching Pokemon with autocatcher on [IMAGE]

### ISSUE THREAD

**Issue by AckroyJR** [Hyperclaw79/PokeBall-SelfBot#119]
https://gyazo.com/9152fea5a7157714a8352f05c7aa01eb

Got my Discord Token but still not catching anything by itself? :'( os there a way u can make this process automatic?

**Comment by Hyperclaw79** [comment]
As clearly stated in the readme, Autocatcher is a Premium Version feature. Please read the readme before opening an issue.
