### ISSUE TITLE
Aiohttp login error

### ISSUE THREAD

**Issue by etch286** [Hyperclaw79/PokeBall-SelfBot#12]
![unbenannt](https://user-images.githubusercontent.com/38834663/39406645-22422568-4bba-11e8-8ba1-adcca700e60f.JPG)

**Comment by Hyperclaw79** [comment]
I suspect it's either a firewall problem or an expired token. See if you can reproduce this on another account.

**Comment by Hyperclaw79** [comment]
@etch286 Please let me know if this can be reproduced with another account. I'll close this tomorrow if I get no response, assuming that it is unique to your context.
