### ISSUE TITLE
Error bot in Pokecord ( Autocatch and Command p^ )

### ISSUE THREAD

**Issue by bossmta** [Hyperclaw79/PokeBall-SelfBot#120]
My bot inactive ( Pokecord ). Can not use command p^ . Bot can't autocatch @@ 
![1](https://user-images.githubusercontent.com/43910779/46572618-552ad700-c9b3-11e8-8080-ae08630f72b5.png)
![2](https://user-images.githubusercontent.com/43910779/46572619-552ad700-c9b3-11e8-9385-263dc82fa332.png)

**Comment by Hyperclaw79** [comment]
Your prefix is `P^`, not `p^`. Prefixes are case sensitive.

Also, please read the readme before opening an issue. It's clearly mentioned that Autocatcher will only work in the Premium Version.

**Comment by bossmta** [comment]
@Hyperclaw79  tks pro , but i tried P ^ it still does not work, i think there is error in id reply to message

**Comment by Hyperclaw79** [comment]
It is definitely a local issue as this code was tested.
That being said,
1. Are you using a space between P and ^?
2. Are you sure the token belongs to the account you're logged in from? See the "Bot Name" in the console.

**Comment by bossmta** [comment]
> Nó chắc chắn là một vấn đề địa phương như mã này đã được thử nghiệm. 
> Điều đó đang được nói,
> 
> 1. Bạn đang sử dụng một không gian giữa P và ^?
> 2. Bạn có chắc mã thông báo thuộc về tài khoản bạn đã đăng nhập không? Xem "Tên Bot" trong bảng điều khiển.
Error does not occur here: ((
![image](https://user-images.githubusercontent.com/43910779/46781787-886fbc00-cd4d-11e8-81ad-03656d805824.png)

**Comment by Hyperclaw79** [comment]
If you look at the bot name, the tag is different to that of the account you're logged in as. The confusion is because of the other account with the same name. You need to get the token of the account you're logged in as.

**Comment by bossmta** [comment]
Off .. and on ![image](https://user-images.githubusercontent.com/43910779/46816744-d0bbc800-cda7-11e8-8519-81812c8b10d3.png)
![Uploading image.png…]()

**Comment by Hyperclaw79** [comment]
Dude, a selfbot is not a Discord bot. You are trying to automate a bot
instead of your own account.
