### ISSUE TITLE
Bot is running but not catching?

### ISSUE THREAD

**Issue by pegacat-nest** [Hyperclaw79/PokeBall-SelfBot#122]
# Title: The bot is running but it is not catching my pokemons!

## Problem:
so i have the bot up and running and the responses from cmd told me its running as it should but somehow it is not catching pokemons. Here's what my cmd looks like after I` start run.bat`
![image](https://user-images.githubusercontent.com/38011585/47943417-583eb780-decc-11e8-961c-be4a114e0012.png)

## config.json:
```
{
   "token": "my token",
   "command_prefix": "P^",
   "priority": [],
   "avoid": [],
   "catch_rate": 90,
   "delay": 3,
   "delay_on_priority": false,
   "restrict_duplicates": true,
   "max_duplicates": 2,
   "blacklists": [],
   "whitelists": [],
   "blacklist_guilds": [382316968394620938], 
   "whitelist_guilds": [my private server ID],
   "autolog": true,
   "update_checker": true,
   "auto_update": true,
   "autocatcher": true,
   "priority_only": true
}

```

## Specs.
**OS**: Windows 10
**Bot Version**: v3.3.2
**Python Version**: v3.7

**Comment by Hyperclaw79** [comment]
Why didn't you just read the Readme where it is clearly mentioned that the Autocatcher is now a Premium Version feature?
