### ISSUE TITLE
Manifest

### ISSUE THREAD

**Issue by survivhacker** [Hyperclaw79/PokeBall-SelfBot#125]
When I go on my Chromebook I download the zip then I unzipp it go on chrome://extensions load unpacked then it tell me it can't load tour manifest is there another way to download this?

**Comment by Hyperclaw79** [comment]
I've not tested it on a Chromebook so I can't say for sure if it works but, why are you even going to `chrome://extensions`?? This is not a browser extension. It's a standalone python script that has nothing to do with your browser.

Instructions on running it on ChromeOS is beyond the scope of this repo.

**Comment by survivhacker** [comment]
How do I run the script or whatever to hack pokecord

**Comment by Hyperclaw79** [comment]
Download and extract the zip to your desktop. Then follow the instructions
in the Readme.
