### ISSUE TITLE
Cant contact on discord

### ISSUE THREAD

**Issue by LiqwdE** [Hyperclaw79/PokeBall-SelfBot#128]
# Title: [Bug/Query/(leave empty)] ErrorName

# Body:

## Problem:
Discord hates me, it cant find you. I donated, can you hit me back. LiqwdE#5972

## Steps to Reproduce:
List out the steps you took to come upon the error.

## config.json:
Most of the problems arise due to badly edited config.json. Hence post the contents of it within codeblocks. (Select the contents here and press code button on top.)

## Traceback and Screenshots:
Paste the Traceback/Error here using codeblocks.
Post relevant screenshots.
![image](https://user-images.githubusercontent.com/3068959/52885416-c97e3f80-3136-11e9-86c6-e7396012a597.png)

## Specs.
**OS**:
**Bot Version**:
**Python Version**:

**Comment by Hyperclaw79** [comment]
Sent you the req.
