### ISSUE TITLE
How much is the premiun version? 

### ISSUE THREAD

**Issue by Putusmutus** [Hyperclaw79/PokeBall-SelfBot#131]

**Comment by Hyperclaw79** [comment]
Please read the Readme before opening another issue. Like I've said, all the details are mentioned there.
GitHub Issues is for reporting bugs, not for communicating.

**Comment by Putusmutus** [comment]
I cant understand english porperly, that is why I ask you...

**Comment by Hyperclaw79** [comment]
You can still read numbers right? It clearly says $25 USD. It would be a problem for you if you can't understand English instructions.
