### ISSUE TITLE
How many bots can you run on Premium?

### ISSUE THREAD

**Issue by KentoDX** [Hyperclaw79/PokeBall-SelfBot#132]
Couldn't add you on discord to ask before purchasing. Thanks.

**Comment by Hyperclaw79** [comment]
You can control two bots from a single account but you can have many such pairs.
But with the Advanced Extension, you can control as many bots as you want from a single account,

> Couldn't add you on discord to ask before purchasing. Thanks.

Tell me your discord ID and I'll add you then.
