### ISSUE TITLE
Bot Not AutoCatching

### ISSUE THREAD

**Issue by RonWilsonBus** [Hyperclaw79/PokeBall-SelfBot#133]
# Title: [Bug/Query/(leave empty)] Not Catching Anything

# Body: Hi. I finally got everything working except for the catching aspect. Everything works (Including echo so I know it has my token) except for the auto part of the bot.

## Problem:
Everything works (Including echo so I know it has my token) except for the auto part of the bot.
(See picture)

## Steps to Reproduce:
Restrict catching of duplicates is off, but I still put the max amount of duplicates to 999. I whitelisted the server, and channel. There is a 1 second delay. Auto catcher is automatically turned on

## config.json:
{
   "token": "Token goes here, but I ain't gonna show it",
   "command_prefix": "P^",
   "priority": [],
   "avoid": [],
   "catch_rate": 99,
   "delay": 1,
   "delay_on_priority": false,
   "restrict_duplicates": false,
   "max_duplicates": 999,
   "blacklists": [],
   "whitelists": [Token goes here, but I ain't gonna show it],
   "blacklist_guilds": [382316968394620938],
   "whitelist_guilds": [Token goes here, but I ain't gonna show it],
   "autolog": true,
   "update_checker": true,
   "auto_update": true,
   "autocatcher": true,
   "priority_only": false
}

## Traceback and Screenshots:
Paste the Traceback/Error here using codeblocks.
Post relevant screenshots.
![unknown](https://user-images.githubusercontent.com/48879551/54877864-c2fc7b00-4dfa-11e9-8f7e-8fcb6c522db6.png)
![e](https://user-images.githubusercontent.com/48879551/54877868-c8f25c00-4dfa-11e9-89d9-5bf70633a70b.png)

## Specs.
**OS**: W10
**Bot Version**: Newest
**Python Version**: 3.72

**Comment by Hyperclaw79** [comment]
As stated in the Readme, autocatcher is now a Premium Version only feature.
Refer the Donations section for further details about Premium Version.
