### ISSUE TITLE
Error while opening setup

### ISSUE THREAD

**Issue by AmarilloBoop** [Hyperclaw79/PokeBall-SelfBot#136]
![cmd_Ac2qLl4MZh](https://user-images.githubusercontent.com/50748290/57941818-3046fc80-78d0-11e9-8c99-a4564607b7f5.png)

Followed instructies as written. When opening setup.bat I get this error.

Keep in mind I am no programming or coding hero.

**Comment by Hyperclaw79** [comment]
**Disclaimer**
> The Public Version isn't maintained anymore so you're bound to run into more errors. Getting the Premium Version is highly recommended.

You need to change the contents of `requirements.txt` to just `discord`.

*This change is necessary since the rewrite version of discord.py is now the official one.*
