### ISSUE TITLE
jsondecode error

### ISSUE THREAD

**Issue by faggut** [Hyperclaw79/PokeBall-SelfBot#137]
## Steps to Reproduce:
I restarted the bot using P^restart and i came across this error

## config.json:
```
{
   "token": "!!!",
   "command_prefix": "P^",
   "priority": [
      "Pikachu",
      "Haxorus",
      "Unown"
   ],
   "avoid": [],
   "catch_rate": 100,
   "delay": 0,
   "delay_on_priority": false,
   "restrict_duplicates": false,
   "max_duplicates": 2,
   "owner_id": "!!!!",
   "blacklists": [],
   "whitelists": [],
   "default_mode": "blacklist",
   "blacklist_guilds": [
      382316968394620938
   ],
   "whitelist_guilds": [],
   "default_guildmode": "blacklist",
   "allowed_users": [],
   "alts": [],
   "autolog": false,
   "autocatcher": true,
   "priority_only": false,
   "log_level": "Default",
   "iv_threshold": 50,
   "autoclaim": false
}
```

## Traceback and Screenshots:
https://imgur.com/g1uErIc
[yo wdf](https://user-images.githubusercontent.com/51277189/58755210-2a812600-8522-11e9-9193-2c5664f57515.png)

## Specs.
**OS**:Windows 10
**Bot Version**:
**Python Version**:3.6

**Comment by Hyperclaw79** [comment]
Judging from the config, this is a Premium Version based issue. It's some minor mistake in your configs. Contact me on Discord instead.
