### ISSUE TITLE
Pokeball Selfcatcher error

### ISSUE THREAD

**Issue by wend500** [Hyperclaw79/PokeBall-SelfBot#138]
# Title: Bot Error

## Problem:
Pokeball Selfcatcher not working when the pokemon is showing it didnt do anything, but when i use P^echo test , it responded. 

## Specs.
**OS**:Windows
**Bot Version**:v3.3.2
**Python Version**:3.7.3

**Comment by Hyperclaw79** [comment]
As clearly stated in the Readme, autocatcher works only in the Premium Version. Read the Donations section for full details of what all are included.
