### ISSUE TITLE
still work?

### ISSUE THREAD

**Issue by wilison1992** [Hyperclaw79/PokeBall-SelfBot#139]
Just wonder is it still safe? By the way, wrong discord ID.

**Comment by wilison1992** [comment]
My dis id: CRAZYEVEN#5644

**Comment by Hyperclaw79** [comment]
Yes still works and is safe. I'm referring to the Premium Version btw, not the public one here.

My Discord ID isn't wrong, maybe you didn't copy it properly.

I've added you on discord now.
