### ISSUE TITLE
New user here . need some help ^^ 

### ISSUE THREAD

**Issue by mahmud7849** [Hyperclaw79/PokeBall-SelfBot#14]
so i have followed every instruction but still cant get it working . it appears and tells me to press any key to continue and when i do that it disappears instantly . i am using 64bit windows 10 , and python 3.6.0(64 bit)

would really appreciate if you can help ^^ 
![untitled](https://user-images.githubusercontent.com/38952582/39587313-024c70b0-4f1b-11e8-8d02-29287d7feee6.png)
![untitled2](https://user-images.githubusercontent.com/38952582/39587326-08e86af0-4f1b-11e8-9023-9e6555280dbf.png)
![untitled3](https://user-images.githubusercontent.com/38952582/39587333-0e7a4b64-4f1b-11e8-8037-467beb66d161.png)

**Comment by mahmud7849** [comment]
Thanks for the fast reply . I downloaded https://www.python.org/downloads/release/python-365/ , this and installed 3.6.5 ( Windows x86-64 executable installer , for AMD64/EM64T/x64 ) , but the problem still persists .  still shows the same problem in command box . What am i doing wrong ? D:

**Comment by Hyperclaw79** [comment]
Do a `pip freeze` and show me the whole output.

**Comment by mahmud7849** [comment]
![untitled](https://user-images.githubusercontent.com/38952582/39623728-65d325a0-4fb8-11e8-80cc-928ea0afc8fb.png)
do you mean this ? x,x

**Comment by mahmud7849** [comment]
![untitled2](https://user-images.githubusercontent.com/38952582/39623965-486a72a6-4fb9-11e8-9e85-d5c0b161b979.png)
i also did this , since it said to upgrade pip . @.@

**Comment by Hyperclaw79** [comment]
Hmm, not sure what's going on. Your libraries seem up to date and my code seems to be working flawlessly for others. The error you're getting an aiohttp bug.

Try reinstalling discord.py using `pip install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]`

**Comment by mahmud7849** [comment]
Thanks for responding so quickly . sadly its still not working ;c . Thanks for all the help and thanks for the bot ^^
