### ISSUE TITLE
Self Bots against Discord TOS :/

### ISSUE THREAD

**Issue by PatheticMustan** [Hyperclaw79/PokeBall-SelfBot#143]
Just a tip, Discord Self Bots are completely forbidden by the Discord TOS :/

**Comment by Hyperclaw79** [comment]
1. It's not a valid issue.
2. I've already mentioned it in the Readme. Please read the readme completely before opening up an issue.
3. As per the disclaimer, the users are solely responsible for the actions. This repo itself isn't a violation of Discord ToS.
4. Discord usually flags selfbot accounts that put stress on their systems through spamming, etc.
The code makes sure that such a limit is not hit. I've rarely had any users report about bans unless they didn't follow the instructions or made their own modifications.
