### ISSUE TITLE
How do i do this?

### ISSUE THREAD

**Issue by Mathurans09** [Hyperclaw79/PokeBall-SelfBot#144]

**Comment by Hyperclaw79** [comment]
> added and did everything

What exactly did you do? Cause setting the config file comes under the "everything".

For setting the config, just open the file with Notepad or any text editor and change the values as per the readme.

**Comment by Mathurans09** [comment]
Ok so I found my token key to the bot and added it to my config file but when I do run.bat im getting errors and it says timout

**Comment by Hyperclaw79** [comment]
Next time, screenshots would help. But I'm guessing you're getting `Python not found in the path` error.
To fix this, go to Start -> Remove/Change Programs -> Python. Choose `Modify` on python. Now during the installation, make sure the option `Add Python to the path` or `Add python as environment variable` is enabled. Rerun setup.bat after that.

**Comment by Mathurans09** [comment]
ok so u want me to reinstall python??

**Comment by Mathurans09** [comment]
Here is a screenshot of what happens after I run run.bat.
![image](https://user-images.githubusercontent.com/57379471/68254029-7c5d3900-fff7-11e9-98a3-6f1de4bae009.png)

**Comment by Hyperclaw79** [comment]
You need python version 3.6, not 3.8.

**Comment by Mathurans09** [comment]
Ok now I realized after changing my python the token key wasn't added. So I added that too and here is what I got. 
![image](https://user-images.githubusercontent.com/57379471/68254844-ad3e6d80-fff9-11e9-8626-c0289b5f25bb.png)

**Comment by Mathurans09** [comment]
and here is how it looks on my config.json file 
![image](https://user-images.githubusercontent.com/57379471/68254891-c9daa580-fff9-11e9-86d0-ffc00edf3d1f.png)

**Comment by Mathurans09** [comment]
and if its the case in downloading 3.6 where would I find it and could u give me the download link??

**Comment by Mathurans09** [comment]
I was running python 3.6 and its still showing the same message

**Comment by Hyperclaw79** [comment]
Judging from the size, your token is invalid. Check in YouTube for "how to
get a discord Selfbot token" and try again. Make sure you copy paste it
correctly.

P.S. Easy with the opening and closing there.
