### ISSUE TITLE
Command Help

### ISSUE THREAD

**Issue by Parnasuss-MD** [Hyperclaw79/PokeBall-SelfBot#145]
# Title: Command Help

# Body:

## Problem:
I can't seem to get the commands to work for mass releasing.

## Steps to Reproduce:
I typed in discord P^pokelog entered it in discord and it produced the message "No prefix found for this guild"
I am trying to use the P^mass_release command and from reading notes it says I need to do the P^ pokelog first then use P^mass_release.

## config.json:
{
   "token": "Private Token",
   "command_prefix": "P^",
   "priority": [
      "Groudon",
	  "Mew",
      "Machop",
      "Staryu"
   ],
   "avoid": [],
   "catch_rate": 90,
   "delay": 3,
   "delay_on_priority": false,
   "restrict_duplicates": true,
   "max_duplicates": 2,
   "blacklists": [],
   "whitelists": [],
   "blacklist_guilds": [382316968394620938],
   "whitelist_guilds": [Private Guild],
   "autolog": true,
   "update_checker": true,
   "auto_update": true,
   "autocatcher": false,
   "priority_only": false
}

## Traceback and Screenshots:
Paste the Traceback/Error here using codeblocks.
Post relevant screenshots.
![image](https://user-images.githubusercontent.com/59327371/71552974-ae29c500-29d4-11ea-8852-79444983d9ec.png)

## Specs.
**OS**: Win 10
**Bot Version**: v3.3.2
**Python Version**: 3.8

**Comment by Hyperclaw79** [comment]
You need to turn on the Developer Mode on your Discord, right-click on your server's icon and get the guild ID and alter `guilds.json` to include:
 ```json
{
   guild_id:"pokecord prefix in that guild"
}
```

**Comment by Parnasuss-MD** [comment]
I did change it in the file already and had developer mode on as well but still nothing. 

![image](https://user-images.githubusercontent.com/59327371/71560518-d77c3c80-2a38-11ea-9905-97c41cbd5869.png)

**Comment by Hyperclaw79** [comment]
Hmm are you sure that the guild IDs are correct/of the correct servers?  And these servers are in your whitelist_guilds? Also, did you restart the bot after changing your guilds.json?

**Comment by Parnasuss-MD** [comment]
Yes so I got it to work after I did P^pokelog then typed in p!pokemon and it logged everything however after it finished logging things it started giving me an error and I couldn't move forward with P^mass_trash.

**Comment by Hyperclaw79** [comment]
First of all it's, `P^mass_release dupes`
Secondly, post the error which you got.

**Comment by Hyperclaw79** [comment]
Closing this cause of inactivity. Feel free to reopen by posting the error.
