### ISSUE TITLE
ImportError: cannot import name 'Deque'

### ISSUE THREAD

**Issue by SakOf7** [Hyperclaw79/PokeBall-SelfBot#152]
# Title: [Bug] ImportError: cannot import name 'Deque'

# Body:

## Problem:
I am trying to set up the PokeBall bot for the first time, downloaded the prerequisites of Python 3.6, including it in the path and followed all the steps for installation but could not get it to work.

## Steps to Reproduce:
I was following the steps in the installation, clicked the setup.bat, that ran it's course and closed. I then entered my token into the config.json and clicked run.bat as the steps instructed.

This is where I received the following: 
![image](https://user-images.githubusercontent.com/61815934/75947756-65d9c800-5e99-11ea-998f-9c1765ebbb47.png)

## config.json:
Most of the problems arise due to badly edited config.json. Hence post the contents of it within codeblocks. (Select the contents here and press code button on top.)

`{
   "token": "mfa....w",
   "command_prefix": "P^",
   "priority": [
      "Groudon",
	  "Mew",
      "Machop",
      "Staryu"
   ],
   "avoid": [],
   "catch_rate": 90,
   "delay": 3,
   "delay_on_priority": false,
   "restrict_duplicates": true,
   "max_duplicates": 2,
   "blacklists": [],
   "whitelists": [],
   "blacklist_guilds": [382316968394620938],
   "whitelist_guilds": [],
   "autolog": true,
   "update_checker": true,
   "auto_update": true,
   "autocatcher": false,
   "priority_only": false
}
`

![image](https://user-images.githubusercontent.com/61815934/75947864-b18c7180-5e99-11ea-8b11-c467df1ef248.png)

## Traceback and Screenshots:
Paste the Traceback/Error here using codeblocks.
Post relevant screenshots.

## Specs.
**OS**: Windows 10
**Bot Version**: Latest version available on Github
**Python Version**: 3.6

**Comment by Hyperclaw79** [comment]
Open a command prompt and run `pip install -U discord.py`.

Also, you seem to be using 2 Factor Authentication. In that case you'll need to stay logged in on discord while using the bot.

**Comment by SakOf7** [comment]
Just tried it and got the following: 

![image](https://user-images.githubusercontent.com/61815934/75982738-26ce6580-5edf-11ea-8e40-08cf8a144654.png)

**Comment by SakOf7** [comment]
Just entered the command and got the following: 
![image](https://user-images.githubusercontent.com/61815934/75983001-96dceb80-5edf-11ea-816e-856197b320ea.png)

**Comment by SakOf7** [comment]
When doing 'run.bat' I am currently getting: 
![image](https://user-images.githubusercontent.com/61815934/75983141-dd324a80-5edf-11ea-86d0-a6f1f7f32925.png)

**Comment by Hyperclaw79** [comment]
Looks like your initial problem has been fixed. Perhaps, you forgot to run the `setup.bat` or had a different virtual environment active during the execution of `run.bat` the previous time.

Moving on, now you're probably trying to run it on a main account or an account which is in multiple server. Due to discord's recent changes in how it handles guild chunking for user accounts, the bot never reaches a ready state.
So, try running the bot on a fresh account until a fix is released.

**Comment by SakOf7** [comment]
Hi, tried it on a fresh account and it has worked.

For it to work on my main account will I need to leave a bunch of servers?

**Comment by Hyperclaw79** [comment]
No, leaving does't help. I'll be coming up with a fix for this in the
Premium Version soon.
