### ISSUE TITLE
Bot running, but not catching

### ISSUE THREAD

**Issue by fredrikie** [Hyperclaw79/PokeBall-SelfBot#153]
I know discord updated some api stuff not long ago. Is the bot not working or am i doing something wrong. 

Autocatcher is on, i spammed some text in my server and a poke spawned, but the bot did not catch.

lemme know.
thanks!

**Comment by Hyperclaw79** [comment]
Not sure how you've missed it, but it's clearly stated in the readme that the Autocatcher is a part of the Premium Version. Of course it will not work in the public version.
