### ISSUE TITLE
Bot on_ready issue

### ISSUE THREAD

**Issue by Maywij** [Hyperclaw79/PokeBall-SelfBot#158]
i run run.bat and not thing happen 
![image](https://user-images.githubusercontent.com/57218301/77817328-a1fcf300-70fc-11ea-8246-92d6691b79a3.png)
here is my config.json {
   "token": "MjQ0MDgxNzM0OTk4NTU2Njcy.XhCn4Q.SvFD3p6EZPKnI05dJyKGlPXXEvQ",
   "command_prefix": "P^",
   "priority": [
      "Groudon",
	  "Mew",
      "Machop",
      "Staryu"
   ],
   "avoid": [],
   "catch_rate": 99,
   "delay": 2,
   "delay_on_priority": false,
   "restrict_duplicates": true,
   "max_duplicates": 2,
   "blacklists": [],
   "whitelists": [],
   "blacklist_guilds": [382316968394620938],
   "whitelist_guilds": [],
   "autolog": true,
   "update_checker": true,
   "auto_update": true,
   "autocatcher": true,
   "priority_only": false
}

**Comment by Hyperclaw79** [comment]
Due to recent changes in Discord's API, the bot will not load anymore for accounts which are in multiple servers. To use it, consider a fresh account.

_P.S. There's a workaround for it and has been implemented in the Premium Version._
