### ISSUE TITLE
Trying to run public version and it didn't work

### ISSUE THREAD

**Issue by ID7OoMy** [Hyperclaw79/PokeBall-SelfBot#163]
# Title: the bot  not working

# Body:after making the setup right and everything i put my account token and then opened the run.bat
and it says py -3 launcher.py timeout -1 nothing more after i put the P^autocatcher on to start it in the discord server i saw nothing then started to spam words to spawn a pokemon after a pokemon spawn nothing happen it didn't catch so i catched it myself then restarted the run.bat then i putted again P^autocatcher on but nothing happend again started spaming till a pokemon spawn and still it didn't auto catch it even tho i tried it on a browser and on discord desktop 

## Problem:
the self-bot not working 
even after i followed the steps
## Steps to Reproduce:
started the setup then putted my token in config.jason then started the run.bat 

## config.json:
```
{
   "token": "my token was here",
   "command_prefix": "P^",
   "priority": [
      "Groudon",
	  "Mew",
      "Machop",
      "Staryu"
   ],
   "avoid": [],
   "catch_rate": 90,
   "delay": 3,
   "delay_on_priority": false,
   "restrict_duplicates": true,
   "max_duplicates": 2,
   "blacklists": [],
   "whitelists": [],
   "blacklist_guilds": [382316968394620938],
   "whitelist_guilds": [],
   "autolog": true,
   "update_checker": true,
   "auto_update": true,
   "autocatcher": false,
   "priority_only": false
}
```

## Traceback and Screenshots:
there is nothing that i can take screenshot of since there wasn't like error log 
## Specs.
**OS**:Windows
**Bot Version**:3.3.2
**Python Version**:3.7.7

**Comment by Hyperclaw79** [comment]
As clearly mentioned in the Readme, Autocatcher is premium version only. Please read the readme before opening issues.
