### ISSUE TITLE
Cant get the Bot to work .-.

### ISSUE THREAD

**Issue by PikaArc** [Hyperclaw79/PokeBall-SelfBot#2]
When i try to launch the bot i get a "KeyError" then a "timeout -1" .-. any idea why?
![screenshot_4](https://user-images.githubusercontent.com/26232927/37874098-0d87f484-3028-11e8-98ee-5dabe3f456fb.png)

**Comment by ElectroArc** [comment]
ok... got the keyerror fixed (With the closed issue) but now i get this :-: 
![image](https://user-images.githubusercontent.com/26232927/37874347-87c986f4-302d-11e8-94be-80e9d17aa84e.png)

**Comment by PikaArc** [comment]
and now this? wtf i added 1 pokemon as priority (which is Pikachu cause i love it)
![image](https://user-images.githubusercontent.com/26232927/37874583-ff8a1664-3031-11e8-96af-ce6b9a519106.png)

**Comment by PikaArc** [comment]
no help needed more this issue can get closed

**Comment by mous1331** [comment]
How did you fix both of those issues?

**Comment by Hyperclaw79** [comment]
@PikaArc @mous1331 JSON is case sensitive. Also make sure you're using proper Syntax as per the examples.
Mous, can you post your `configs.json` file? Then I can point you to the mistake.

Also guys, some updates are still pending to be made. So do check the repo again tomorrow.

**Comment by mous1331** [comment]
I finally got the bot running, didn't realise I had to replace the os line in the secrets. Now I come across issues when I P^pokelog and P^clean_trash
**P^pokelog**
![](https://cdn.discordapp.com/attachments/422448766747148290/427535163308900392/unknown.png)
**P^clean_trash**

![](https://cdn.discordapp.com/attachments/422448766747148290/427536326850772992/unknown.png)
