### ISSUE TITLE
Message.guild AttributeError

### ISSUE THREAD

**Issue by Stranger94** [Hyperclaw79/PokeBall-SelfBot#22]
![image](https://user-images.githubusercontent.com/35736068/40337217-8b07d8fc-5d6e-11e8-9dbf-1763455f0011.png)

What does that mean?
It lauched perfectly without error (so it showed me settings, like 2 sec delay, whitelist etc in cmd). Next it spams only this text...
It doesnt catch me pokemon.
I put channel id in whitelist. This also not worked, so I inserted my channel id into pokeball.py. Still no catching.

What do I miss?

**Comment by Hyperclaw79** [comment]
Hmm, this happens when you get DMs but not sure why this error is popping up for you.
Technically, `message.guild` should return `None` instead of an AttributeError.
Possibly a change in `discord.py`. Well, I'll send a fix for it soon along with other fixes.
