### ISSUE TITLE
Setup Guide with visuals

### ISSUE THREAD

**Issue by Stranger94** [Hyperclaw79/PokeBall-SelfBot#25]
The bot works for me I have this screen:

![image](https://user-images.githubusercontent.com/35736068/40373521-5b53ac34-5de7-11e8-9d57-795af18aa415.png)

I assume, it should now be active in that 1 channel.
But, when a Pokemon spawns there, the bot does nothing (same screen). Not even p!catch Uv2624239weg27e. Log is also same. 

So there is maybe 1 part missing in "How to make the bot work".

This all sadly cannot help now anymore if it cannot catch anyway because the changed Pokecord.
I'm still curious about that. And wanna help you that next time you can give 1-2 sentence more in description. Because you put so much work into it that nobody could use it, everyone open new issues, just because there is not 1 picture of for example your cmd window and how it looks if all works + if you catch something with it how it looks.

Very nice anyway :)

**Comment by Hyperclaw79** [comment]
Thank you for the descriptive feedback, I appreciate it. The documentation, aka., a help command for all the other commands is in the roadmap. But I see your point about visuals for basic setup. I'll add it to my ToDo list.

Now, as for your problem, the solution is simple. Your autocatcher is `Off` by default. To enable it, you need to use a command `P^autocatcher on`.

If you don't want to turn it on everytime you restart the bot, simply change the line 41:
```py
self.auto_catcher = False
```
to 
```py
self.auto_catcher = True
```

**Comment by Stranger94** [comment]
Ty, I could have read the code. But I read it with editor and there was no lines, just 1 big block. Good info, because I didn't know what to type in discord to change settings.

**Comment by Hyperclaw79** [comment]
oh btw, if you are using an editor, I suggest [Visual Studio Code](https://code.visualstudio.com). It is a must have for any coder.
It has many built-in plugins ranging from syntax highlighting to built-in compilers.

**Comment by Stranger94** [comment]
I have Visual Studio, but also I have only a slow Laptop and don't want to open Visual Studio, if it works quick in editor too :D

**Comment by Stranger94** [comment]
I don't know why, but the commands get no reaction.

I change in pokeball catcher in line 41 to true. It doesnt catch or write anything.

**Comment by Stranger94** [comment]
What I do is close + run setup.bat as admin.

The commands in discord doesn't work. Now I copied everything into System32 and started it as Admin, it still doesn't work.
And although auto_catcher is "true" (I changed the file and did restart etc) it does nothing.

In console it shows me all till whitelist and there is no change after everything (spawn, command). 

How I use it: With my account spamming chat with Pokecord. Pokemon spawns. I wait but my Account dont write from the bot. Should I log out? Dumb questions maybe, but I would like to make it work.

**Comment by Hyperclaw79** [comment]
> Now I copied everything into System32 and started it as Admin, it still doesn't work.

Not necessary.

>I wait but my Account dont write from the bot

I didn't get you. You need to use the commands from the same account as your selfbot.
The multi-user mode is available in Premium version.

**Comment by Stranger94** [comment]
I do, same account. But bot does nothing. Idk why :(

**Comment by Stranger94** [comment]
And I copied into System32 because it gave me error, that he can't find launcher, ect when I start as admin. If I start normal it not neccassary

**Comment by Hyperclaw79** [comment]
Do not run it as Admin. You don't have to. Run it from the same folder
where all the files are there.

Try sending `P^echo test` in the chat and see if the bot replies `test`.

**Comment by Hyperclaw79** [comment]
Looks like the commands itself are not running. That is why, launch it normally from the directory where the original file is, and in normal mode. No need of admin.

The fact that even echo command is not working means the bot isn't able to communicate with Discord after it logs in.

Add python as exception to your firewall.

**Comment by Stranger94** [comment]
![image](https://user-images.githubusercontent.com/35736068/40388749-9a85bad6-5e10-11e8-8e78-ddeb5f3fba2b.png)

**Comment by Stranger94** [comment]
Python always opens in C:\Windows\System32
uff

I give up.
I disabled firewall whole day today.
And I started it whole day except 1 time without admin. If I don't know what to do I test all 100 ways.

You want to know what for me is the hardest part about programming or using cmd? Because the error todays are ALL about directories and shit. Really I wasted 1 day on this and it still doent work because now I have everywhere .py and discord files. Again jump 4 hours back reinstall phyton the 5th time? Or should I reinstall the bot files 5th time after deleting all files? 

Ty for the help but I will try it maybe next week, since it looks like you cant catch pokemon now anyways.

**Comment by Stranger94** [comment]
![image](https://user-images.githubusercontent.com/35736068/40389755-748f424a-5e13-11e8-92b9-0c999754e328.png)

**Comment by Stranger94** [comment]
I think that's the fatal problem, which also appears for other self-bots.

**Comment by Hyperclaw79** [comment]
Hmm, looks like that PR was a bad move.
I can fix this pip issue, not a problem.

As for the folder location, just download the zip file and extract it to Desktop, go into the folder, run `setup.bat` and then run `run.bat`.

Try adding this line 
```py
print(message.content)
``` 
at line 116 to see if the bot is atleast reading the messages.

```py
async def on_message(self, message):
    def pokecord_reply(msg):
        return msg.author.id == 365975655608745985
    print(message.content)
    if not self.ready:
        return
```

Make sure you follow proper indentation while adding that line.

**Comment by Stranger94** [comment]
Okay I will try that as soon as possible, thank you for the help :) I will stay here I can learn something and you can fix stuff.

**Comment by BFruchtfliege** [comment]
maybe a bad question :-P where i can find line 41 for autostart. i looked at all files. there is no line 41 or autostart :/

**Comment by BFruchtfliege** [comment]
Thought i deleted my post, because i found the file a few seconds lauter :-p
Ty for answer and helping

**Comment by Hyperclaw79** [comment]
Closing this as it feels excessive with all the provided details in the Readme and as preparation for a future major change.
