### ISSUE TITLE
Unable to edit files

### ISSUE THREAD

**Issue by NoOne681** [Hyperclaw79/PokeBall-SelfBot#26]
It just opens in chrome and i cant edit it or anything. Plz fix or im prob doing something wrong.

**Comment by Hyperclaw79** [comment]
You are supposed to download the zip and then work on the local copy.

**Comment by Hyperclaw79** [comment]
Can you post the screenshots of what exactly you are trying to do?

**Comment by Hyperclaw79** [comment]
Closing this as there was no response from the OP.
Assuming it is solved. Moreover this is not an issue directly related to the bot.

Feel free to reopen later.
