### ISSUE TITLE
Aiohttp Error

### ISSUE THREAD

**Issue by aale12** [Hyperclaw79/PokeBall-SelfBot#28]
I've got and aiohttp problem.  I've read through issues #12, #14, and #21 and it seems to be similar to #21.  I'ved tried what you've told him to do and it seems to still not work.  I would donate if I could get the bot to work.  Any help would be greatly appreciated.

![cmd_2018-05-23_17-44-57](https://user-images.githubusercontent.com/39572738/40455175-6a4260bc-5eb1-11e8-9eec-03f29e89ebac.png)

Above is the error, and below is me trying to do pip install -U aiohttp:

![cmd_2018-05-23_17-48-21](https://user-images.githubusercontent.com/39572738/40455206-92007850-5eb1-11e8-88de-3022be284f0b.png)

**Comment by Hyperclaw79** [comment]
What I've found out is that `discord.py` doesn't work with just any version of `aiohttp` even if it is the latest one.
So I have hardcoded the version to `2.2.5` in https://github.com/Hyperclaw79/PokeBall-SelfBot/commit/036806e560cc1343e7e802038e9ac299d7d0f504 as `dicord.py` requires between `2.0.0 - 2.3.0`.

Please uninstall aiohttp with `pip uninstall aiohttp` and run the `setup.bat` from the latest zip.

**Comment by aale12** [comment]
Still having the same problem.  I'll check back on this project at a future date and see then.  Thanks for your work.  You can close this issue.

**Comment by Hyperclaw79** [comment]
I will temporarily close this now. Feel free to open it up in the future.

**Comment by Hyperclaw79** [comment]
@aale12 I know I've closed this as requested but, can you tell me what you see as the version number for `aiohttp` when you execute `pip freeze`?

**Comment by Hyperclaw79** [comment]
@mkanter124
@supersquid86
@MateeTheGod

Can all of you please try executing that `pip freeze` in your command prompts and see the version number for aiohttp?

**Comment by MateeTheGod** [comment]
Ive downloaded python 3.65 and it doesnt allow me to use pip commands

**Comment by Hyperclaw79** [comment]
@MateeTheGod you are supposed to execute them in cmd, not from within python.
Moreover, simply download the latest version. You don't need to do pip again.

**Comment by aale12** [comment]
![cmd_2018-05-25_15-08-47](https://user-images.githubusercontent.com/39572738/40564259-988c598c-602d-11e8-9191-bad4ae7aa6b2.png)
Here's what I see using pip freeze.  I'll check out the new zip right now though.

**Comment by aale12** [comment]
Can confirm it's working for me now.  Thanks for the update! Really appreciate it.

**Comment by mkanter124** [comment]
Thank you kindly @Hyperclaw79 . Beautifully made bot and sorry for making a duplicate issue. Thank you for all your help! ;)

**Comment by Hyperclaw79** [comment]
Glad that it's working for you guys :D
Now I can close this issue in peace. ✌️
