### ISSUE TITLE
Aiohttp Error like usual, feelsbad

### ISSUE THREAD

**Issue by mkanter124** [Hyperclaw79/PokeBall-SelfBot#29]
I know a lot of people have already posted this problem, but I've been reading all the attempted fixes and nothing seems to work. I've tried reinstalling python, uninstalling aiohttp and then running setup.bat again but I just keep getting this:
![desktop screenshot 2018 05 24 - 15 57 44 87 2](https://user-images.githubusercontent.com/39601864/40510747-9d334800-5f6b-11e8-998b-e8ce76282183.png)
Hopefully, I can help. Maybe I could figure it out if I was guided through or we troubleshoot?

**Comment by Hyperclaw79** [comment]
Please don't open a new issue if there is an existing one. Just subscribe to the single issue so that you can keep a track of it.
