### ISSUE TITLE
Unknown Message Error

### ISSUE THREAD

**Issue by mous1331** [Hyperclaw79/PokeBall-SelfBot#3]
I finally got the bot running, didn't realise I had to replace the os line in the secrets. Now I come across issues when I P^pokelog and P^clean_trash. I also can't seem to get the autocatcher to work, It has been enabled however whenever a pokemon spawns in an enabled guild it doesn't do anything.
**P^pokelog**
![](https://cdn.discordapp.com/attachments/422448766747148290/427535163308900392/unknown.png)
**P^clean_trash**

![](https://cdn.discordapp.com/attachments/422448766747148290/427536326850772992/unknown.png)

This is my config, haven't really touched it 
![](https://cdn.discordapp.com/attachments/422448766747148290/427537030193348618/unknown.png)

This is my guild's file.
![](https://cdn.discordapp.com/attachments/422447445448982560/427543728698294272/unknown.png)

**Comment by mous1331** [comment]
Ok I have sort of fixed my issue with P^clean_trash, in order to use it I had to set max_duplicates lower to 2 .

**Comment by Hyperclaw79** [comment]
Actually, both the issues are with `pokelog` and not with `clean_trash`. The latter calls the former after the cleaning is done.

>max_duplicates lower to 2

Shouldn't make a difference. But woah, you've set it to 200. That's like you wanna catch 200 of the same pokemon for every pokemon. Set to max 4 or 5 tbh.

>I also can't seem to get the autocatcher to work, It has been enabled however whenever a pokemon spawns in an enabled guild it doesn't do anything.

Does the typing get activated in that channel when the pokemon spawns?

**Comment by PikaArc** [comment]
Hello again from me ^^ I launched the bot succesfully but it seems to doesnt do anything .-. (my command prefix is ,) when i execute ,pokelog the cmd prompt gives back : No Prefix found for this guild
and by clean_trash it doesnt do anything nor responds in the cmd prompt... and auto catching doesnt work either

**Comment by Hyperclaw79** [comment]
Fixed in https://github.com/Hyperclaw79/PokeBall-SelfBot/commit/6b3f4df14718d157ad922522654158508526c5ff.

@PikaArc Looks like you are manually altering the guilds.json. 
Don't do this, the selfbot automatically adds the guild prefix upon catching a pokemon in that guild.
