### ISSUE TITLE
No idea whats wrong

### ISSUE THREAD

**Issue by MateeTheGod** [Hyperclaw79/PokeBall-SelfBot#30]
![image](https://user-images.githubusercontent.com/39608467/40522559-2ac79d76-5f97-11e8-8a84-a68e3ec3cd2f.png)
would love if you could help
also might be good to mention that i dont know how to run the pip commands

**Comment by Hyperclaw79** [comment]
Please don't open a new issue if there is an existing one. Just subscribe to the single issue so that you can keep a track of it.
