### ISSUE TITLE
py : Not Recognised as Command Issue

### ISSUE THREAD

**Issue by DaSpookyMan** [Hyperclaw79/PokeBall-SelfBot#34]
I recently downloaded all the files and edited the config, put in my server token and tinkered with the code to make the self bot work how I wanted it to, (true, false, pokemon names, etc.) Upon setting it up which only took 1 second before the cmd window closed, the run.bat file instantly comes up with the text shown below in the screenshot. 
![screenshot 12](https://user-images.githubusercontent.com/39640576/40572254-5ddb5974-60ea-11e8-90e6-d2c790632856.png)
If someone can please explain this to me, it would be a big help!

**Comment by Hyperclaw79** [comment]
Looks like you either don't have python installed or don't have it in the path.
Trying replacing `py -3` in run.bat with `python`. If it doesn't work, reinstall python and make sure you add it to path.

> put in my server token

You are supposed to put in your user token. wdy,m server token?

**Comment by DaSpookyMan** [comment]
Thanks for the quick response. By server token, I meant user token and I think the problem has to do with me not having python. I'm installing it right now and giving it a spin. Hopefully it works

**Comment by DaSpookyMan** [comment]
I've installed Python and the bot looked like it started up right, though when I try use p^autocatcher on, nothing happens. What could be going on?
![screenshot 13](https://user-images.githubusercontent.com/39640576/40574008-186feff2-610e-11e8-90a2-759fa96d2e59.png)
![screenshot 14](https://user-images.githubusercontent.com/39640576/40574010-18c070f8-610e-11e8-937e-97c78ce4be82.png)

**Comment by Hyperclaw79** [comment]
Can you see anything being printed out on the console?
And are you using the commands from the same account as to which the token
belongs to?
