### ISSUE TITLE
TypeError: must be in str, not list

### ISSUE THREAD

**Issue by Dragooness** [Hyperclaw79/PokeBall-SelfBot#35]
I get that when I try to run the bot. I KNOW its probably my fault, I have no clue what I am doing can you help me please?

![image](https://user-images.githubusercontent.com/39663604/40582398-d3a7ed0c-613a-11e8-93c6-1295af76d847.png)

Also when I get the bot running, is there a more detailed "User manual" Like how to use the built in spammer?

**Comment by Dragooness** [comment]
I tried clearing out local storage closing out and logging back in and I get the same error.

**Comment by Hyperclaw79** [comment]
Can you show me your `config.json` with a few characters in your token censored? Also, show the line in your `secret.py` where you pasted the token.

> is there a more detailed "User manual"

A Help Command is on the project Roadmap. Will implement it soon.

> how to use the built in spammer

This is available only on Premium Version.

**Comment by Dragooness** [comment]
{
   "token": [
      "pretend a token is here"
   ],
   "command_prefix": "P^",
   "priority": [
      "Groudon",
      "Mew",
      "Machop",
      "Staryu"
   ],
   "avoid": [],
   "catch_rate": 90,
   "delay": 3,
   "delay_on_priority": false,
   "restrict_duplicates": true,
   "max_duplicates": 3,
   "blacklists": [],
   "whitelists": []
}

**Comment by Dragooness** [comment]
I copied and replaced, using the one downloaded with the bot and got the same result

**Comment by Hyperclaw79** [comment]
See, that's the problem. Why did you encase your token within a list(`[]`)?
It should just be encased in `""`.
```json
{
"token": "Mxsfg.3f3f3gdd_6885w......",
"command_prefix": "P^",
"priority": [
"Groudon",
"Mew",
"Machop",
"Staryu"
],
"avoid": [],
"catch_rate": 90,
"delay": 3,
"delay_on_priority": false,
"restrict_duplicates": true,
"max_duplicates": 3,
"blacklists": [],
"whitelists": []
}
```
