### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by EndingNight** [Hyperclaw79/PokeBall-SelfBot#4]
The bot no longer works it guesses the image's filename which is now just a random mess of letters and numbers i.e. : p!catch UcdyiCKAZMY instead of : p!catch vullaby

**Comment by Hyperclaw79** [comment]
Yes pretty much. So the selfbot's autocatcher mode is down for now.
You can continue using the other features of the bot. More improvements and new features coming soon.
Stay tuned.
