### ISSUE TITLE
Doesn't work. 

### ISSUE THREAD

**Issue by Emma324** [Hyperclaw79/PokeBall-SelfBot#5]
I've followed every single step required for run this.  and to prove that i'm doing it right is that the other self-bot that this is an extension of, works perfectly.

you stated this had bulk-trading so I felt that would be awesome but it just won't work.

**Comment by Hyperclaw79** [comment]
Few of the updates are still pending. Will be done soon. Also, can you post the logs or the error which concludes that this doesn't work for you?

**Comment by Hyperclaw79** [comment]
And it is now fixed. Reopen this if you had a different issue.
