### ISSUE TITLE
Unable to toggle autocatcher

### ISSUE THREAD

**Issue by LilPuS** [Hyperclaw79/PokeBall-SelfBot#51]
I am typing P^autocatcher on in my discord and it isn't doing anything, where do i type P^autocatcher on to turn it on

**Comment by Hyperclaw79** [comment]
Can you please post your `config.json`?
Is `P^` your command prefix?
Are you sending the command from the same account from where you got the token?

**Comment by LilPuS** [comment]
nvm fixed it but how do i use the auto trade you state you have 'A trade command to bulk trade the pokemon to your main account.'. How do i use it

**Comment by Hyperclaw79** [comment]
Let's say you wanna trade the mons with ids 1234, 666 and 69,
`P^trade @main 1234 666 69` 
Or, you can move your entire fav list
`P^trade @main fav`
Or, move every pokemon except those in the priority_list (not recommended cause of pokecord's lag)
`P^trade @main`
