### ISSUE TITLE
Obsolete Python Version on Linux 

### ISSUE THREAD

**Issue by ithecookie** [Hyperclaw79/PokeBall-SelfBot#52]
When I type pip install -r requirements.txt 
```
I get this back Collecting discord.py from https://github.com/Rapptz/discord.py/archive/rewrite.zip#egg=discord.py (from -r requirements.txt (line 1))
  Downloading https://github.com/Rapptz/discord.py/archive/rewrite.zip (960kB)
    100% |████████████████████████████████| 962kB 1.3MB/s 
Collecting aiohttp<2.3.0,>=2.0.0 (from discord.py->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/1e/d4/c1206b016b42a0b223aadb559318966b64ec27e5406bed79c36356e62082/aiohttp-2.2.5.tar.gz
    Complete output from command python setup.py egg_info:
    aiohttp/_http_parser.pyx: cannot find cimported module '.'
    Compiling aiohttp/_websocket.pyx because it depends on /home/james/.local/lib/python2.7/site-packages/Cython/Includes/cpython/weakref.pxd.
    Compiling aiohttp/_http_parser.pyx because it depends on /home/james/.local/lib/python2.7/site-packages/Cython/Includes/cpython/weakref.pxd.
    [1/2] Cythonizing aiohttp/_http_parser.pyx
    [2/2] Cythonizing aiohttp/_websocket.pyx
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-u7AyzC/aiohttp/setup.py", line 66, in <module>
        raise RuntimeError("aiohttp requires Python 3.4.2+")
    RuntimeError: aiohttp requires Python 3.4.2+
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-u7AyzC/aiohttp/
```
Please Help

**Comment by Hyperclaw79** [comment]
It is clear that you are using an older version of python.
The requirements says `Python 3.6`.
So, upgrade your python first.

**Comment by ithecookie** [comment]
I'm still having same problem after updating

**Comment by ithecookie** [comment]
Collecting yarl<1.2 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/91/14/5983db75b143681058d31a0a89a770f40a7f68f9b94cfeb6e6495b0039bf/yarl-1.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-q42q7M/yarl/setup.py", line 1, in <module>
        import pathlib
    ImportError: No module named pathlib
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-q42q7M/yarl/

**Comment by Hyperclaw79** [comment]
install `pathlib` first using `sudo pip install pathlib` and retry.

**Comment by Hyperclaw79** [comment]
@ithecookie Since I didn't get any response for a whole day and it isn't a bug in the bot, I'll be closing this down for now assuming that it has been solved. Feel free to reopen it if needed.
