### ISSUE TITLE
Python 3.6 still wont work

### ISSUE THREAD

**Issue by ithecookie** [Hyperclaw79/PokeBall-SelfBot#53]
~/Downloads/PokeBall-SelfBot-master $ pip install -r requirements.txt
Collecting yarl<1.2 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/91/14/5983db75b143681058d31a0a89a770f40a7f68f9b94cfeb6e6495b0039bf/yarl-1.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-q42q7M/yarl/setup.py", line 1, in <module>
        import pathlib
    ImportError: No module named pathlib
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-q42q7M/yarl/

**Comment by Hyperclaw79** [comment]
Let's reopen the original issue and move to there.
