### ISSUE TITLE
[Duplicate] Mac Deployment Issues

### ISSUE THREAD

**Issue by pazzaro** [Hyperclaw79/PokeBall-SelfBot#56]
I did everything according to read me and corrected everythin in a new folder then the terminal keeps saying  "SSID_CERTIFICATE_VERIFY_FAILED" i tried updating pip tru terminal but then it says its up to date?

**Comment by Hyperclaw79** [comment]
Please reopen your other issue and move to there.
But I am not sure about this current one as it doesn't seem to be related to the bot.

**Comment by pazzaro** [comment]
i did it wrong again? sorry

**Comment by pazzaro** [comment]
sorry i shouldt waste ur time lol sorry really ima go
