### ISSUE TITLE
Python Path Issue

### ISSUE THREAD

**Issue by SCP-7007** [Hyperclaw79/PokeBall-SelfBot#58]
So I have created my own bot as a selfbot and did the steps accordingly, but the step where you have to replace the os.environ["DISCORD_BOT_TOKEN"] in secret.py with a bot token is frustratingly confusing. I mean I did replaced it with my bot token, run the run.bat but I keep on having the error:

line 261, in static_login
    raise LoginFailure('Improper token has been passed.') from e
discord.errors.LoginFailure: Improper token has been passed.

May I have a visual help? I am struggling to get this working ;-; ....

**Comment by Hyperclaw79** [comment]
Alright, looks like many people are having a problem with this. I'll get rid of this extra step to edit `secret.py` and leave it commented out for the advance users to work on later.

For now, just paste the token in the `config.json` directly.

The syntax should be exactly like `"token":"mxyadefefged4rt3f3f4"`.

**Comment by SCP-7007** [comment]
Hello! Thank you for the response. I have done just simply pasting the token at the config.json directly then hit run.bat. But then now I received an error message

\Programs\Python\Python36-32\lib\os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'DISCORD_BOT_TOKEN'

Am I doing something wrong here? Or should I wait for the changes and fix on the SelfBot?

**Comment by Hyperclaw79** [comment]
This has been fixed just now in https://github.com/Hyperclaw79/PokeBall-SelfBot/commit/7d18d8f19cd1f6442fdb9bb8e22f1e045b9fe233.

The `secret.py` overwrites the token in `config.json` and that's why you were getting that error. 
Now I have commented it out and you'll be good to go. Download the latest one.

**Comment by Hyperclaw79** [comment]
Post a screenshot of your `config.json` contents. Censor out a few characters in the token,

**Comment by Vividead** [comment]
![2018-05-30 17_51_54-c__windows_system32_cmd exe](https://user-images.githubusercontent.com/39772863/40732020-a9d22f24-6432-11e8-87db-36665b422129.png)

Any idea what is wrong? I think I pasted token correctly

**Comment by Hyperclaw79** [comment]
Looks like you either don't have python installed or it's not in your path.
Modify your installation and select `Add Python to Environment Variable` option.
