### ISSUE TITLE
Another Deployment Issue

### ISSUE THREAD

**Issue by MrMaster12** [Hyperclaw79/PokeBall-SelfBot#59]
Yo, I've done everything the tutorial says but I can't get it to work. is there anything I'm missing?
I made an alt account, got the token, placed it in config.json, ran setup, then run.

## config.json:
```
{
   "token": "<Already there>",
   "command_prefix": "p^",
   "priority": [
],
   "avoid": [],
   "catch_rate": 90,
   "delay": 3,
   "delay_on_priority": false,
   "restrict_duplicates": true,
   "max_duplicates": 5,
   "blacklists": [],
   "whitelists": [451XXXXXXXXXXXXXXX]
}

```
is there anything I missed, plz let me know..

**Comment by Hyperclaw79** [comment]
Can you try launching `launcher.py` instead of `run.bat` and see if there is an error there?

**Comment by Hyperclaw79** [comment]
Please switch to the latest version, which gets rid of this hassle.
Simply paste the token in `config.json` instead as per new instructions in the readme.

**Comment by MrMaster12** [comment]
Sorry for being stupid, but how do I get the latest version..

**Comment by Hyperclaw79** [comment]
Just download the zip again.

**Comment by MrMaster12** [comment]
Oh okay, It's working now.. Thanks a lot bro :)

**Comment by Hyperclaw79** [comment]
You're welcome 😃

**Comment by MrMaster12** [comment]
Btw I've got something for the next update. 
Change the name of 'flabebe' to 'flabébé' cuz u can't catch it otherwise

**Comment by Vividead** [comment]
![2018-05-30 17_51_54-c__windows_system32_cmd exe](https://user-images.githubusercontent.com/39772863/40731819-2c9e59ec-6432-11e8-8d03-51154222d714.png)

I have no idea what is wrong

**Comment by Hyperclaw79** [comment]
@MrMaster12 Feel free to open up a PR on it. Working on bigger things atm. 😅

**Comment by MrMaster12** [comment]
Ye ofc, ik it's nothing just wanted to point this out. I love your work and I'm waiting to see what's coming up. Keep it up bro 👌

**Comment by Hyperclaw79** [comment]
Thank you 😄

**Comment by MrMaster12** [comment]
Hey man.. So my farming is going good except for one thing.. The bot doesn't catch all Pokemon that appear for some reason sometimes one, two or three Pokemon in a row. I didn't really care about that in the beginning, but after I missed a mew and a rayquaza this morning I was really mad.. And no, I do not have any Pokemon on my avoid list..
