### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by Fr0sTy7u7** [Hyperclaw79/PokeBall-SelfBot#6]
I cant find where os.environ is and do I need to make my alt like a discord bot?

**Comment by Hyperclaw79** [comment]
It's at in `secret.py`. Just get rid of the whole `os.environ[....` and replace it with your token as a string, i.e. `"enter your token here token"`.

> like a discord bot?

Wdym like a discord bot? Just make a normal account. That's the whole difference between a selfbot and a discordbot.

**Comment by Fr0sTy7u7** [comment]
Can you make a video on it or something im hopeless I dont understand anything about Python :( but you are good at code with Python keep up the work 👍 🥇

**Comment by Hyperclaw79** [comment]
Thanks for the compliment.
Unfortunately, this code is meant for those with a basic understanding of Python. Even if I do help you out here, you're bound to run into lot of queries in the future. So, I suggest you first learn the basics of Py.

In secret.py,

Replace `configs["token"] = os.environ["DISCORD_BOT_TOKEN"]` with `configs["token"] = "your token here"`.
Refer the tutorial linked in the readme to get the token.

**Comment by Fr0sTy7u7** [comment]
Oh yes, haha I have figured that part out but it isn't working its giving me some sort of time out or an error when im trying to run it.

**Comment by Hyperclaw79** [comment]
hmm that will happen only for a token error.
Can you post an ss of your secret.py and config,json with a few letters in
your token censored?

**Comment by Fr0sTy7u7** [comment]
![capture](https://user-images.githubusercontent.com/38487364/38972879-06d46fe4-4358-11e8-80fa-fd4f447545f2.PNG)

**Comment by Fr0sTy7u7** [comment]
![nice](https://user-images.githubusercontent.com/38487364/38972921-23cc8cbc-4358-11e8-8a0b-135779e69482.PNG)

**Comment by Fr0sTy7u7** [comment]
![noice](https://user-images.githubusercontent.com/38487364/38972933-343a59b2-4358-11e8-81ab-aece9d1816a2.PNG)

**Comment by Fr0sTy7u7** [comment]
and I added the last one so I could understand if thats secret.py or no. :)

**Comment by Fr0sTy7u7** [comment]
![test](https://user-images.githubusercontent.com/38487364/38973092-df9ff226-4358-11e8-9ab0-66b3d3a74c89.PNG)

**Comment by Hyperclaw79** [comment]
Two things:
```md
1. You did not replace the token like I told you to in your secret.py. It is apparent from your traceback.
2. You are using the wrong command_prefix. p! belongs to PokeCord. Your selfbot's prefix needs to be unique. 
```
And lmfao, when I said ss of secret.py, I meant the content, not the file name 😂

**Comment by Fr0sTy7u7** [comment]
OMG Do I replace the token into run.bat  and change my prefix to something like x_

**Comment by Hyperclaw79** [comment]
>Do I replace the token into run.bat

No! secret.py
run.bat is just a windows batch file. Nothing to do with your token. Read my previous replies properly, you'll figure it out.

> change my prefix to something like x_

Yes.

**Comment by Fr0sTy7u7** [comment]
But I still dont know which secret file you are talking about, the one I tried to open was a python file named '"secret" and it didnt let me open it, it closed really quick. :(

**Comment by Hyperclaw79** [comment]
First of all it's a selfbot (which is against ToS), making a video about is
an overkill.
Anyways, don't double-click the python file. Instead, right-click and open
it with Notepad (or any other text editor).
Make the changes and save it. Then you're good to go.

**Comment by Fr0sTy7u7** [comment]
![yay](https://user-images.githubusercontent.com/38487364/39002972-a8065fac-43ae-11e8-896c-d50991109db4.PNG)

**Comment by Fr0sTy7u7** [comment]
Is that how its supposed to be

**Comment by Fr0sTy7u7** [comment]
![noo](https://user-images.githubusercontent.com/38487364/39003020-c2e6e6de-43ae-11e8-90a3-edfd4241e977.PNG)

**Comment by Fr0sTy7u7** [comment]
Cause its still giving me timeouts after that :(

**Comment by Hyperclaw79** [comment]
hmm looks like your session expired. Try getting the token again and using the new one instead.

**Comment by Fr0sTy7u7** [comment]
Okay, so if I do it with a new token itll work right, right?? :D

**Comment by Hyperclaw79** [comment]
>how do I turn on the autocatcher and turn it off

Read the source code. All the function that start with `cmd_` can be used from discord. Simply replace the `cmd_` with your desired prefix. In your case, p^. 

For example, `p^pokelog` to use the pokelog command. Some commands will onluy work if you give them args, i.e., extra instructions. For example, you cannot use the `echo` command without giving the message to echo.
i.e.,
`p^echo` won't work. You need to specify it as `p^echo my message`. 

Also, the order of the args matter too. Keep that in mind. For example, `p^id Bulba search` won't work. It should be `p^id search Bulba`.

This is the exact reason why you need to have a knowledge of python to properly use this selfbot.

>And does the bat stay open like that or does it close on its own

You need to close it by yourself after you are done selfbotting.

**Comment by Fr0sTy7u7** [comment]
And whats the command to turn the auto-catcher on and I think I found a bug 
![lol](https://user-images.githubusercontent.com/38487364/39049053-94db5918-4454-11e8-8db8-456dee73e83c.PNG)

**Comment by Hyperclaw79** [comment]
ah, not exactly a bug but this happens when you don't have at least one
whitelist channel and one blacklist channel.

**Comment by Fr0sTy7u7** [comment]
Haha, when I put in a whitelist channel that happens. But I have figured out how to self-bot so no worries.
