### ISSUE TITLE
Toggle Modes

### ISSUE THREAD

**Issue by Logixx00** [Hyperclaw79/PokeBall-SelfBot#60]
Hello, I am confused on all of the different modes you can switch to. The toggle_mode command seems to react to anything you put in a the parameter so I was wondering. What are the official modes for the bot?

**Comment by Hyperclaw79** [comment]
Ah, that's a small indentation mismatch so it prints it despite not executing it.
Only `Whitelist` and `Blacklist` are the supported options. 
Will be fixed in the next update.

**Comment by Logixx00** [comment]
Ok thank you. What do those two do btw?

**Comment by Hyperclaw79** [comment]
As explained in the Readme, **Blacklist** mode means, the bot will work in **all** the channels/guilds that are **not** in the **blacklist**.
In **Whitelist** mode, the bot will work **only** in the channels/guild that are there in the **whitelist**.

**Comment by Logixx00** [comment]
Ok sorry I asked, I didn't think to look there. Thank you for your help
