### ISSUE TITLE
PokeBall.py syntax error

### ISSUE THREAD

**Issue by Arkansas640** [Hyperclaw79/PokeBall-SelfBot#61]
## Problem:
whenever i try to run the Run.bat file, i get this error message

![image](https://user-images.githubusercontent.com/39781938/40753065-52e922fe-6440-11e8-8e8e-facb4bd3a57c.png)

im not sure what i could be missing for this to occur

## config.json:
`{
   "token": "my token here",
   "command_prefix": "P^",
   "priority": [
      "Groudon",
	  "Mew",
      "Rayquaza",
      "Kyogre"
   ],
   "avoid": [],
   "catch_rate": 90,
   "delay": 3,
   "delay_on_priority": false,
   "restrict_duplicates": true,
   "max_duplicates": 3,
   "blacklists": [],
   "whitelists": [numbers here],
   "blacklist_guilds": [numbers here],
   "whitelist_guilds": [numbers here],
   "autolog": false
}`

## Specs.
**OS**:
Windows 10
**Bot Version**:
v3.2.1
**Python Version**:
Python 3.6

**Comment by 3sixtyied** [comment]
Having the same problem!

**Comment by Hyperclaw79** [comment]
Oops, bad copy paste 😅 
Fixed it in https://github.com/Hyperclaw79/PokeBall-SelfBot/commit/802e77f072859d67b3fb466505dec9891e6919cd. 👍
