### ISSUE TITLE
Turning capital letters off

### ISSUE THREAD

**Issue by Vividead** [Hyperclaw79/PokeBall-SelfBot#63]
Hello,

How can I turn capital letters off? It looks less suspicious when the bot doesn't use them in pokemon names

**Comment by Hyperclaw79** [comment]
Hmm, there is no such option as of now. You can create a request at the Feature Requests.
<a href="http://feathub.com/Hyperclaw79/PokeBall-SelfBot"><img src="https://cdn.rawgit.com/Hyperclaw79/PokeBall-SelfBot/8da8c6dd/pika%2B1.png" width="100" height="100" alt="Feature Requests"/></a>
