### ISSUE TITLE
PLS ADD AN OPTION TO DISABLE VERBOSE

### ISSUE THREAD

**Issue by pazzaro** [Hyperclaw79/PokeBall-SelfBot#65]
PLS ADD OPTION TO DISABLE VERSION THX

**Comment by Hyperclaw79** [comment]
Hmm, there is no such option as of now. You can create a request at the Feature Requests.
<a href="http://feathub.com/Hyperclaw79/PokeBall-SelfBot"><img src="https://cdn.rawgit.com/Hyperclaw79/PokeBall-SelfBot/8da8c6dd/pika%2B1.png" width="100" height="100" alt="Feature Requests"/></a>

Do explain in detail what exactly you wanna accomplish.
