### ISSUE TITLE
Misplaced session object

### ISSUE THREAD

**Issue by Principito37** [Hyperclaw79/PokeBall-SelfBot#66]
I've tried to download the newest version of the bot, but it keeps downloading version 320. It doesn't matter if I "git clone" or download the zip. However, the problem starts up once I activate the bot to autocatch. The problem is that every time a pokemon spawns, the attribute error is shown. I have looked through previous issues and could not find anything similar to this problem. 
![capture](https://user-images.githubusercontent.com/30328147/40798612-b295b892-64c8-11e8-9c16-f5a36f941abc.PNG)

**Comment by Dragooness** [comment]
I have the same error, I have reverted to using the old version until there's a fix

**Comment by Hyperclaw79** [comment]
I didn't face this issue on the premium version. I'll look into it and fix it by evening.

**Comment by Hyperclaw79** [comment]
Fixed it in https://github.com/Hyperclaw79/PokeBall-SelfBot/commit/1ab991d32ca3f6076489eb21ace8d817c458c84e.
