### ISSUE TITLE
Guild Mode

### ISSUE THREAD

**Issue by Dragooness** [Hyperclaw79/PokeBall-SelfBot#67]
Is this a premium feature? As I use P^toggle_guildmode and get no response, I would really like to not have to do it chanel by chanel!

Also setting duplicate to true or false yields no difference, everything is still caught and the bot tells me restricting is off.

Also when restricting, is there a way to prevent specific pokemon from being limited at all? Theres a few things I need extras of, what I dont need is 10 friggin caterpie.

Also the new version isnt catching right. It skipped a Porygon2 and a dratini with a whole bunch of random things all in a row.

**Comment by Dragooness** [comment]
Fixed the other issues, except the Guildmode. I thought I had it fixed, so I rejoined the official pokechord server and the bot went WILD. SO I got banned. So I will be using previous version for now XD

**Comment by Hyperclaw79** [comment]
My condolences for your ban but you should have tested it on your private server first.
Since you have not provided your `config.json`, I cannot assist you further.
Please follow the issue template in order to help me debug.
Reopen the issue after you post the required details.
