### ISSUE TITLE
Api.github.com Server Closes Connection

### ISSUE THREAD

**Issue by MateeTheGod** [Hyperclaw79/PokeBall-SelfBot#70]
# Title: [Bug/Query/(leave empty)] ErrorName

# Body:

## Problem:
After pressing run it just says the name of the bot and where its located, after like a minute or so it'll have an error

## Steps to Reproduce:
I pressed run and waited a minute and the error popped up

## config.json:
Most of the problems arise due to badly edited config.json. Hence post the contents of it within codeblocks. (Select the contents here and press code button on top.)

`https://vgy.me/KMK1gJ.png`

## Traceback and Screenshots:
https://vgy.me/uzKPiB.png

## Specs. sorry, i dont know, but i can say that the old version worked for me
**OS**: Windows 10
**Bot Version**: Latest Version
**Python Version**: Python 3.6

**Comment by Hyperclaw79** [comment]
From the error, it is apparent that one of the servers in your account is either down due to temporary outage or banned you from there while the bot was loading. Try re-running it.
Also, try running it with another account.
Your configs seem to be fine, so this might be just a temporary issue.

Do let us know if you're able to get it working or if you come across a new error.

**Comment by MateeTheGod** [comment]
i am about to access the version file, and i assume you mean quick restart chrome, i will try that now

**Comment by Hyperclaw79** [comment]
Quick restart the bot lol, not chrome.

**Comment by MateeTheGod** [comment]
])
        try:
            blackies = '\n'.join([
                ', '.join([str(channel) for channel in self.configs['blacklists'][i:i+5]]) for i in range(0, len(self.configs['blacklists']), 5)
            ])
        except:
            blackies = "None"
        try:    
            whities = '\n'.join([
                ', '.join([str(channel) for channel in self.configs['whitelists'][i:i+5]]) for i in range(0, len(self.configs['whitelists']), 5)
            ])

**Comment by Hyperclaw79** [comment]
Starting from `headers =` till `print(bordered(vtext))`

**Comment by MateeTheGod** [comment]
headers = {"Accept": "application/vnd.github.v3.raw+json"}
        async with aiohttp.ClientSession(headers=headers, loop=self.loop) as sess:
            async with sess.get("http://api.github.com/repos/Hyperclaw79/PokeBall-SelfBot/contents/_version.json") as resp:
                data = await resp.read()
        data = json.loads(data)    
        vnum = int(data["version"].split('v')[1].replace('.', ''))
        lnum = int(self.version.split('v')[1].replace('.', ''))
        if vnum > lnum:
            vtext = f'{"_"*79}\nThere is a new version available. Download it to for new updates and bug fixes.\n'
            vtext += f'Your version: {lnum}\nNew Version: {vnum}\n{"_"*79}'
            print(vtext)
        priorities = self.configs['priority']
        prio_list = '\n'.join([
            ', '.join(priorities[i:i+5]) for i in range(0, len(priorities), 5)
        ])
        try:
            blackies = '\n'.join([
                ', '.join([str(channel) for channel in self.configs['blacklists'][i:i+5]]) for i in range(0, len(self.configs['blacklists']), 5)
            ])
        except:
            blackies = "None"
        try:    
            whities = '\n'.join([
                ', '.join([str(channel) for channel in self.configs['whitelists'][i:i+5]]) for i in range(0, len(self.configs['whitelists']), 5)
            ])
        except:
            whities = "None"
        print(
            "\n---PokeBall SelfBot {self.version}----\n\n"
            f"Bot name: {self.user}\n\n"
            f"Command Prefix: {self.configs['command_prefix']}\n\n"
            f"Priority:\n~~~~~~~~~\n{prio_list}\n\n"
            f"Catch Rate: {self.configs['catch_rate']}%\n\n"
            f"Catch Delay: {self.configs['delay']} seconds\n\n"
            f"Delay On Priority: {'On' if self.configs['delay_on_priority'] == True else 'Off'}\n\n"
            f"Restrict Catching of Duplicates: {'On' if self.configs['delay_on_priority'] == True else 'Off'}\n\n"
            f"Maximum Number of Duplicates: {self.configs['max_duplicates']}\n\n"
            f"Blacklisted Channels:\n~~~~~~~~~~~~~~~~~~~~\n{blackies}\n\n"
            f"Whitelisted Channels:\n~~~~~~~~~~~~~~~~~~~~\n{whities}\n\n"
        )
        self.ready = True

**Comment by MateeTheGod** [comment]
headers = {"Accept": "application/vnd.github.v3.raw+json"}
        async with aiohttp.ClientSession(headers=headers, loop=self.loop) as sess:
            async with sess.get("http://api.github.com/repos/Hyperclaw79/PokeBall-SelfBot/contents/_version.json") as resp:
                data = await resp.read()
        data = json.loads(data)    
        vnum = int(data["version"].split('v')[1].replace('.', ''))
        lnum = int(self.version.split('v')[1].replace('.', ''))
        if vnum > lnum:
            vtext = f'{"_"*79}\nThere is a new version available. Download it to for new updates and bug fixes.\n'
            vtext += f'Your version: {lnum}\nNew Version: {vnum}\n{"_"*79}'
            print(vtext)

**Comment by Hyperclaw79** [comment]
Comment that part out in the code.
Add `#` in front of each line in that block.

**Comment by Hyperclaw79** [comment]
Yes, do that in your `pokeball.py` and try running the bot again.

**Comment by MateeTheGod** [comment]
you're a genius, it worked :D

**Comment by Hyperclaw79** [comment]
Glad that it worked. The only drawback is that you'll have to manually keep a look out for new updates and download them.

**Comment by MateeTheGod** [comment]
i had to do that anyways, i never got any updates
