### ISSUE TITLE
Problem running run.bat

### ISSUE THREAD

**Issue by BoiBoisBoi** [Hyperclaw79/PokeBall-SelfBot#72]
# Title: [It won't run the bot] Errno 10060

# Body: The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\dogem\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 224, in _run_event
    yield from coro(*args, **kwargs)
  File "C:\Users\dogem\Desktop\PokeBall-SelfBot-master\pokeball.py", line 645, in on_ready
    async with sess.get("http://api.github.com/repos/Hyperclaw79/PokeBall-SelfBot/contents/_version.json") as resp:
  File "C:\Users\dogem\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\client.py", line 603, in __aenter__
    self._resp = yield from self._coro
  File "C:\Users\dogem\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\client.py", line 231, in _request
    conn = yield from self._connector.connect(req)
  File "C:\Users\dogem\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\connector.py", line 383, in connect
    .format(key, exc.strerror)) from exc
aiohttp.client_exceptions.ClientConnectorError: [Errno 10060] Cannot connect to host api.github.com:80 ssl:False [Can not connect to api.github.com:80 [Connect call failed ('192.30.255.116', 80)]]
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x07708350>
Terminate batch job (Y/N)?
^C
C:\Users\dogem\Desktop\PokeBall-SelfBot-master>timeout -1

## Problem:
Upon running run.bat we discovered an error which prevented us from running. It it says errno 10060 cannot connect to host api.github.com:80

## Steps to Reproduce:
So I downloaded the zip-file selfbot then extracted the file to the desktop. Then I ran setup.bat once that was finished. I configured the file and placed in my token. Then when I ran run.bat I came across this error.

## config.json:
{
   "token": "MjY5Mjk1MTk5MDgyMTE5MTY5.DfNf_w.8mj9byEsBKwz4VTxM9FLTDciiTk",
   "command_prefix": "P^",
   "priority": [
      "Groudon",
	  "Mew",
      "Machop",
      "Staryu"
   ],
   "avoid": [],
   "catch_rate": 90,
   "delay": 3,
   "delay_on_priority": false,
   "restrict_duplicates": true,
   "max_duplicates": 2,
   "blacklists": [],
   "whitelists": [452792045795409920],
   "blacklist_guilds": [382316968394620938],
   "whitelist_guilds": [],
   "autolog": true
}

## Traceback and Screenshots:
![capture](https://user-images.githubusercontent.com/39896748/40899774-ac986f78-681c-11e8-947f-ad01897c1f75.PNG)

## Specs.
AMD A6-7310 APU R4 2.00 GHZ
RAM 8.00 (6.97 Usable)
64 Bit OS
AMD Radeon(TM) R4 Graphics

**OS**: Windows 10
**Bot Version**: {"version":"v3.2.2"}
**Python Version**: 3.6.5

**Comment by Hyperclaw79** [comment]
Looks like a problem with your proxy settings or github might've temporarily timed out.

Refer to this [SO answer](https://stackoverflow.com/questions/15820739/python-urlerror-urlopen-error-errno-10060) for details.

Temporarily closing this as it is not purely a bot issue. Feel free to reopen it if you cannot manage to get it fixed in the future. Good luck. 👍
