### ISSUE TITLE
Obselete Python Version

### ISSUE THREAD

**Issue by Johnny1900** [Hyperclaw79/PokeBall-SelfBot#75]
## Problem:
The problem is that I keep getting a syntax error. Hope you can help.

## Steps to Reproduce:
I downloaded the requirements, and tried running the bot with python3 launcher.py

## Traceback
```
Traceback (most recent call last):
  File "launcher.py", line 2, in <module>
    from pokeball import PokeBall
  File "/home/johnny/Downloads/pokeball/pokeball.py", line 165
    return f"{name} -> {number} -> {level}"
                                          ^
SyntaxError: invalid syntax

```
## Specs.
**Linux**:
**3.2.1**:
**3.6**:

**Comment by Hyperclaw79** [comment]
Since you are getting a syntax error on Fstrings, upgrade your python to `3.6.4`.

**Comment by Johnny1900** [comment]
Thanks, I upgraded python to 3.6.5 and it works now.

**Comment by Hyperclaw79** [comment]
Glad that it worked 😄
