### ISSUE TITLE
Api.Github error

### ISSUE THREAD

**Issue by crunchiboi** [Hyperclaw79/PokeBall-SelfBot#77]
![capture](https://user-images.githubusercontent.com/40080602/41187597-02d0bed6-6bec-11e8-9f34-e2723812c98e.PNG)
whats is this and how do i fix it?

**Comment by Hyperclaw79** [comment]
Looks like you are missing a comma in your `config.json`. Follow the issue template if you want me to find out where exactly.

**Comment by crunchiboi** [comment]
i think i fixed it but now i have this?
![capture1](https://user-images.githubusercontent.com/40080602/41196890-ec44aa7a-6c8a-11e8-9424-d20d80dd44ec.PNG)

**Comment by Hyperclaw79** [comment]
Fixed in https://github.com/Hyperclaw79/PokeBall-SelfBot/commit/150170291d89ed001fa80d18080a71c44fd7bc0c.
