### ISSUE TITLE
Autocatcher queries

### ISSUE THREAD

**Issue by kingkalie** [Hyperclaw79/PokeBall-SelfBot#82]
so i can get it to do the "P^echo test" and it responds with test. but when a new pokemon pops up it doesnt catch it or do anything. i got the "P^autocatcher on" typed in and it shows on the cmd. Activated autocatcher. so not really sure what im doing wrong 
![cfg](https://user-images.githubusercontent.com/40133610/41210995-12f4bee2-6d78-11e8-935b-75cdd8c4033a.PNG)

**Comment by Hyperclaw79** [comment]
lol your catch rate is 25. Bump it up to 85+.

**Comment by kingkalie** [comment]
you said keep it low so i did lol

**Comment by kingkalie** [comment]
and also i couldnt find where to put the autocatch=true command on the config

**Comment by Hyperclaw79** [comment]
Do `P^autocatcher on` in the chat itself.

**Comment by kingkalie** [comment]
also the bot works absolutely great but some of the pokemon dont get caught sometimes like it doesnt pick them up or something and it just skips to the next pokemon when it spawns

**Comment by Hyperclaw79** [comment]
Yes, like I said, it's cause of the catch rate. Set it to 100 and see if it still doesn't catch some.
