### ISSUE TITLE
"improper token has been passed"

### ISSUE THREAD

**Issue by leadheadfred** [Hyperclaw79/PokeBall-SelfBot#84]
![image](https://user-images.githubusercontent.com/21977369/41378799-22ce9054-6f58-11e8-93fe-763e0679c612.png)
![image](https://user-images.githubusercontent.com/21977369/41378820-3158a4f2-6f58-11e8-8125-63f7cfb08808.png)
Whenever i run run.bat i get this and i have no idea what any of it means or what to do about it

**Comment by Hyperclaw79** [comment]
Well it could mean only one thing. The token you are providing in the `config.json` is invalid.
It either expired or is wrongly formatted. Or perhaps you have 2FA enabled which cannot be used for selfbotting.

**Comment by leadheadfred** [comment]
What is 2FA? and i got the token from here and pasted into the speech marks, if it is an invalid token what am i doing wrong? 
![image](https://user-images.githubusercontent.com/21977369/41396549-3b52b37a-6fa9-11e8-8505-9da0728e1c20.png)
![image](https://user-images.githubusercontent.com/21977369/41396566-4a94a5b4-6fa9-11e8-8883-2dd99ad34841.png)

**Comment by Hyperclaw79** [comment]
Lmfao! You are pasting a bot's token. You should paste your own token. Refer
the guide linked in the Readme.  





On Thu, Jun 14, 2018 12:32 PM, leadheadfred notifications@github.com  wrote:
What is 2FA? and i got the token from here and pasted into the speech marks, if
it is an invalid token what am i doing wrong?

**Comment by DynamoYT** [comment]
Why should we have to paste our token?

**Comment by DynamoYT** [comment]
![Uploading Screenshot 2020-09-27 154535.png…]()

**Comment by Hyperclaw79** [comment]
@DynamoYT Cause that's how selfbots work.

**Comment by DynamoYT** [comment]
If I don't want to use a self bot. I want to use a Bot then.

**Comment by Hyperclaw79** [comment]
Then I'm afraid you're the wrong place. Most of the comments here are
targeted towards automating user interactions, hence the selfbot.
