### ISSUE TITLE
Catching Final Evolutions

### ISSUE THREAD

**Issue by PowlandBear** [Hyperclaw79/PokeBall-SelfBot#85]
I want it so the bot can only catch final evolutions, so no pre evos. Also is there a way to turn off the bot so that it doesn't do p!pokemon and then the name of the caught pokemon everytime it catches something.

**Comment by Hyperclaw79** [comment]
> I want it so the bot can only catch final evolutions, so no pre evos

Not gonna spend time on compiling the evos as it is your specific use case. Compile the list yourself and paste them in `priority_list` and turn on `priority_only`.

>turn off the bot so that it doesn't do p!pokemon

That is what autolog is meant for. 

*Please read the Readme properly for config instructions. It's all right there.*
