### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by Irrelevantuser** [Hyperclaw79/PokeBall-SelfBot#88]
Hi Hyperclaw79, I've stumbled upon a issue when trying to set up the bot for myself. I've followed the steps one by one and everything seemed to be going well. When I run the bot it starts up normally and responds to P^echo test and P^autocatcher on. However when I turn on autocatcher the bot keeps on giving me the same error: 

" Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\****\AppData\Local\Programs\
\discord\client.py", line 220, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\****\Desktop\PokeBall-SelfBo
on_message
    name = await self.match(emb.image.url.sp
  File "C:\Users\****\Desktop\PokeBall-SelfBo
match
    return self.pokenames[m]
KeyError: '89de3bad4c1bc7060a8040e1e40c77b0' "

The keyError seems to be different every time and keeps on appearing every 5 seconds or so. the bot doesn't catch pokemon or does any of the other features. Please help!

**Comment by VirtueSuzuya** [comment]
this is the same issue as a already existing issue.... see "pokeball.py issue"

If you look there you can see the reason why, but the short reason to why is due to a update put out by pokecord creator that creates tougher security to prevent auto-catchers.
