### ISSUE TITLE
Run.bat not working

### ISSUE THREAD

**Issue by Glenta** [Hyperclaw79/PokeBall-SelfBot#89]
# Title: [Bug/Query/(leave empty)] ErrorName

# Body:
Hello, I was trying to install the bot and this happened :(

## Problem:
Everytime I try to run run.bat the timeout response popups. 

E:\computer\Downloads\PokeBall-SelfBot-master>py -3 launcher.py
'py' is not recognized as an internal or external command,
operable program or batch file.

E:\computer\Downloads\PokeBall-SelfBot-master>timeout -1

Press any key to continue ...

## Steps to Reproduce:
Installed Git for Windows and Python 3.6.4 32 bit
Downloaded files, and then ran the setup.bat
Changed config file and ran

## config.json:
`{
   "token": "No Token 4 U",
   "command_prefix": "P^",
   "priority": [
      "Groudon",
	  "Mew",
      "Machop",
      "Staryu"
   ],
   "avoid": [],
   "catch_rate": 100,
   "delay": 3,
   "delay_on_priority": false,
   "restrict_duplicates": false,
   "max_duplicates": 2,
   "blacklists": [],
   "whitelists": [454779792366108672,455220210220138506],
   "blacklist_guilds": [382316968394620938],
   "whitelist_guilds": [],
   "autolog": true,
   "update_checker": true,
   "auto_update": true,
   "autocatcher": true,
   "priority_only": false
}`

## Traceback and Screenshots:
`https://i.imgur.com/OhKKNaa.jpg`

## Specs.
**OS**: Windows 10 Pro
**Bot Version**: 3.3.0 ?
**Python Version**: 3.6.4

**Comment by PowlandBear** [comment]
uhh, u try setup.bat yet? Then try run.bat.

**Comment by Glenta** [comment]
I have already ran setup.bat

**Comment by Hyperclaw79** [comment]
Looks like python is not in you path. Go to Uninstall/Change programs, choose Python 3.6 and modify it. Make sure you select `Add Python as Environment Variable` while reinstalling.
