### ISSUE TITLE
help

### ISSUE THREAD

**Issue by wdfghj** [Hyperclaw79/PokeBall-SelfBot#9]
hi, for some reason i cant open your bot
![image](https://user-images.githubusercontent.com/38813420/39400589-98b8cb34-4b33-11e8-9bc2-99baa1445728.png)

![image](https://user-images.githubusercontent.com/38813420/39401006-ebca56fa-4b3b-11e8-9f30-2f35b74d7840.png)

**Comment by Hyperclaw79** [comment]
You've replaced the variable instead of it's value.
It should be, 
```py
configs["token"] = "NDI......WA8"
```

*P.S. You've exposed your account to the world by not censoring your key. I suggest you change your password and get a new key.*
