### ISSUE TITLE
AutoCatcher Don't catch the pokemon

### ISSUE THREAD

**Issue by TheMasterNothing** [Hyperclaw79/PokeBall-SelfBot#91]
## Problem:
When i open the hack  and i active the bot, dont catch the pokemons!! please help

**Comment by Hyperclaw79** [comment]
Please read other issues before opening a new issue. Already tracking this on another Issue.

**Comment by TheMasterNothing** [comment]
You can tell me the name of the issue?

**Comment by Hyperclaw79** [comment]
#87
