### ISSUE TITLE
I'm having trouble running any of the commands

### ISSUE THREAD

**Issue by leadheadfred** [Hyperclaw79/PokeBall-SelfBot#92]
This is probably me being dumb, but when i try to run p^pokelog i get this error
![image](https://user-images.githubusercontent.com/21977369/41497026-d234ae1e-7144-11e8-8dd7-a45b3dd19d23.png)
and when i run p^clean_trash nothing comes up. Am i using the wrong commands?

**Comment by Hyperclaw79** [comment]
As said in the Readme, most of the commands require you to catch at least one pokemon in that guild using the autocatcher. You can manually bypass this. Read the Readme properly for instructions.
