### ISSUE TITLE
Window's could not find setup.bat

### ISSUE THREAD

**Issue by IGhostNI** [Hyperclaw79/PokeBall-SelfBot#97]
I've extracted the file on to my desktop, I tried to set it up but it said Windows could not find setup.bat :/

**Comment by Hyperclaw79** [comment]
Can you post screenshots?
Extract them all into a single folder.

**Comment by IGhostNI** [comment]
![dc6b032ae94ae14232ca2965b9943931](https://user-images.githubusercontent.com/40439330/41678428-0e8b32c8-7499-11e8-9f23-81b68a89cf89.png)

**Comment by IGhostNI** [comment]
my b, heres the screenshot!
![dc6b032ae94ae14232ca2965b9943931](https://user-images.githubusercontent.com/40439330/41678482-2cdb4542-7499-11e8-81cd-050b24c69a11.png)

**Comment by Hyperclaw79** [comment]
Hmm, looks like there's a local issue with your PC. Try your luck on google
for "batch files not being recognized windows".

**Comment by IGhostNI** [comment]
alright
