### ISSUE TITLE
Autocatcher does not work

### ISSUE THREAD

**Issue by Darkskull328** [Hyperclaw79/PokeBall-SelfBot#99]
I have been using it for a while, and it suddenly stopped working. I wonder why?

**Comment by Hyperclaw79** [comment]
As stated in the readme, the autocatcher is now Premium only. The public version one will not work.

**Comment by Darkskull328** [comment]
How do i get Premium version?

**Comment by Hyperclaw79** [comment]
As stated on the readme, it's priced at $25, you need to DM me on Discord.
